use ratatui::style::Color;
use ratatui::symbols::border;

use crate::config::ThemeMode;

#[derive(Debug, Clone, Copy)]
pub(crate) struct Theme {
    pub border_set: border::Set,
    pub header_fg: Color,
    pub header_dim_fg: Color,
    pub footer_fg: Color,
    pub footer_key_fg: Color,
    pub pane_border_fg: Color,
    pub active_pane_border_fg: Color,
    pub divider_fg: Color,
    pub divider_glyph: &'static str,
    pub section_fg: Color,
    pub section_selected_fg: Color,
    pub section_selected_bg: Color,
    pub field_selected_fg: Color,
    pub field_selected_bg: Color,
    pub inactive_selection_fg: Color,
    pub inactive_selection_bg: Color,
    pub tab_fg: Color,
    pub active_tab_fg: Color,
    pub active_tab_bg: Color,
    pub status_ok_fg: Color,
    pub status_error_fg: Color,
    pub status_running_fg: Color,
    pub banner_fg: Color,
    pub table_header_fg: Color,
    pub table_header_bg: Color,
    pub scrollbar_track_fg: Color,
    pub scrollbar_thumb_fg: Color,
    pub section_open_glyph: &'static str,
    pub section_closed_glyph: &'static str,
    pub selection_glyph: &'static str,
    pub inactive_selection_glyph: &'static str,
}

pub(crate) fn theme(mode: ThemeMode) -> Theme {
    match mode {
        ThemeMode::DenseAnsi => Theme {
            border_set: border::PLAIN,
            header_fg: Color::Yellow,
            header_dim_fg: Color::Gray,
            footer_fg: Color::DarkGray,
            footer_key_fg: Color::Cyan,
            pane_border_fg: Color::Gray,
            active_pane_border_fg: Color::Cyan,
            divider_fg: Color::DarkGray,
            divider_glyph: "⋮",
            section_fg: Color::Cyan,
            section_selected_fg: Color::Black,
            section_selected_bg: Color::Cyan,
            field_selected_fg: Color::White,
            field_selected_bg: Color::Blue,
            inactive_selection_fg: Color::White,
            inactive_selection_bg: Color::DarkGray,
            tab_fg: Color::Gray,
            active_tab_fg: Color::Black,
            active_tab_bg: Color::Green,
            status_ok_fg: Color::Green,
            status_error_fg: Color::Red,
            status_running_fg: Color::Yellow,
            banner_fg: Color::Yellow,
            table_header_fg: Color::Black,
            table_header_bg: Color::Gray,
            scrollbar_track_fg: Color::DarkGray,
            scrollbar_thumb_fg: Color::Cyan,
            section_open_glyph: "[-]",
            section_closed_glyph: "[+]",
            selection_glyph: ">",
            inactive_selection_glyph: " ",
        },
        ThemeMode::RichPanel => Theme {
            border_set: border::ROUNDED,
            header_fg: Color::Rgb(255, 204, 77),
            header_dim_fg: Color::Rgb(120, 130, 150),
            footer_fg: Color::Rgb(153, 166, 184),
            footer_key_fg: Color::Rgb(94, 234, 212),
            pane_border_fg: Color::Rgb(85, 98, 116),
            active_pane_border_fg: Color::Rgb(88, 196, 221),
            divider_fg: Color::Rgb(94, 234, 212),
            divider_glyph: "⋮",
            section_fg: Color::Rgb(97, 175, 239),
            section_selected_fg: Color::Rgb(248, 248, 242),
            section_selected_bg: Color::Rgb(51, 84, 129),
            field_selected_fg: Color::Rgb(248, 248, 242),
            field_selected_bg: Color::Rgb(61, 76, 97),
            inactive_selection_fg: Color::Rgb(230, 230, 230),
            inactive_selection_bg: Color::Rgb(55, 62, 72),
            tab_fg: Color::Rgb(160, 174, 192),
            active_tab_fg: Color::Rgb(15, 23, 42),
            active_tab_bg: Color::Rgb(94, 234, 212),
            status_ok_fg: Color::Rgb(134, 239, 172),
            status_error_fg: Color::Rgb(248, 113, 113),
            status_running_fg: Color::Rgb(253, 224, 71),
            banner_fg: Color::Rgb(251, 191, 36),
            table_header_fg: Color::Rgb(15, 23, 42),
            table_header_bg: Color::Rgb(125, 211, 252),
            scrollbar_track_fg: Color::Rgb(47, 56, 66),
            scrollbar_thumb_fg: Color::Rgb(94, 234, 212),
            section_open_glyph: "▾",
            section_closed_glyph: "▸",
            selection_glyph: "▌",
            inactive_selection_glyph: "·",
        },
    }
}
