// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(CasarsFrontendServicesFFI)
import CasarsFrontendServicesFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_casars_frontend_services_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_casars_frontend_services_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCasarsFrontendServicesInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct DatasetProbe {
    public var id: String
    public var name: String
    public var path: String
    public var kind: DatasetKind
    public var sizeBytes: UInt64
    public var modifiedUnixSeconds: UInt64?
    public var probedUnixSeconds: UInt64
    public var logicalSize: String
    public var units: String
    public var fields: [String]
    public var spectralWindows: [String]
    public var scans: [String]
    public var antennas: [String]
    public var correlations: [String]
    public var columns: [String]
    public var dataColumns: [String]
    public var subtables: [String]
    public var shape: [UInt64]
    public var notes: String
    public var diagnostics: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, path: String, kind: DatasetKind, sizeBytes: UInt64, modifiedUnixSeconds: UInt64?, probedUnixSeconds: UInt64, logicalSize: String, units: String, fields: [String], spectralWindows: [String], scans: [String], antennas: [String], correlations: [String], columns: [String], dataColumns: [String], subtables: [String], shape: [UInt64], notes: String, diagnostics: [String]) {
        self.id = id
        self.name = name
        self.path = path
        self.kind = kind
        self.sizeBytes = sizeBytes
        self.modifiedUnixSeconds = modifiedUnixSeconds
        self.probedUnixSeconds = probedUnixSeconds
        self.logicalSize = logicalSize
        self.units = units
        self.fields = fields
        self.spectralWindows = spectralWindows
        self.scans = scans
        self.antennas = antennas
        self.correlations = correlations
        self.columns = columns
        self.dataColumns = dataColumns
        self.subtables = subtables
        self.shape = shape
        self.notes = notes
        self.diagnostics = diagnostics
    }
}

#if compiler(>=6)
extension DatasetProbe: Sendable {}
#endif


extension DatasetProbe: Equatable, Hashable {
    public static func ==(lhs: DatasetProbe, rhs: DatasetProbe) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.sizeBytes != rhs.sizeBytes {
            return false
        }
        if lhs.modifiedUnixSeconds != rhs.modifiedUnixSeconds {
            return false
        }
        if lhs.probedUnixSeconds != rhs.probedUnixSeconds {
            return false
        }
        if lhs.logicalSize != rhs.logicalSize {
            return false
        }
        if lhs.units != rhs.units {
            return false
        }
        if lhs.fields != rhs.fields {
            return false
        }
        if lhs.spectralWindows != rhs.spectralWindows {
            return false
        }
        if lhs.scans != rhs.scans {
            return false
        }
        if lhs.antennas != rhs.antennas {
            return false
        }
        if lhs.correlations != rhs.correlations {
            return false
        }
        if lhs.columns != rhs.columns {
            return false
        }
        if lhs.dataColumns != rhs.dataColumns {
            return false
        }
        if lhs.subtables != rhs.subtables {
            return false
        }
        if lhs.shape != rhs.shape {
            return false
        }
        if lhs.notes != rhs.notes {
            return false
        }
        if lhs.diagnostics != rhs.diagnostics {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(path)
        hasher.combine(kind)
        hasher.combine(sizeBytes)
        hasher.combine(modifiedUnixSeconds)
        hasher.combine(probedUnixSeconds)
        hasher.combine(logicalSize)
        hasher.combine(units)
        hasher.combine(fields)
        hasher.combine(spectralWindows)
        hasher.combine(scans)
        hasher.combine(antennas)
        hasher.combine(correlations)
        hasher.combine(columns)
        hasher.combine(dataColumns)
        hasher.combine(subtables)
        hasher.combine(shape)
        hasher.combine(notes)
        hasher.combine(diagnostics)
    }
}

extension DatasetProbe: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDatasetProbe: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DatasetProbe {
        return
            try DatasetProbe(
                id: FfiConverterString.read(from: &buf),
                name: FfiConverterString.read(from: &buf),
                path: FfiConverterString.read(from: &buf),
                kind: FfiConverterTypeDatasetKind.read(from: &buf),
                sizeBytes: FfiConverterUInt64.read(from: &buf),
                modifiedUnixSeconds: FfiConverterOptionUInt64.read(from: &buf),
                probedUnixSeconds: FfiConverterUInt64.read(from: &buf),
                logicalSize: FfiConverterString.read(from: &buf),
                units: FfiConverterString.read(from: &buf),
                fields: FfiConverterSequenceString.read(from: &buf),
                spectralWindows: FfiConverterSequenceString.read(from: &buf),
                scans: FfiConverterSequenceString.read(from: &buf),
                antennas: FfiConverterSequenceString.read(from: &buf),
                correlations: FfiConverterSequenceString.read(from: &buf),
                columns: FfiConverterSequenceString.read(from: &buf),
                dataColumns: FfiConverterSequenceString.read(from: &buf),
                subtables: FfiConverterSequenceString.read(from: &buf),
                shape: FfiConverterSequenceUInt64.read(from: &buf),
                notes: FfiConverterString.read(from: &buf),
                diagnostics: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: DatasetProbe, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterTypeDatasetKind.write(value.kind, into: &buf)
        FfiConverterUInt64.write(value.sizeBytes, into: &buf)
        FfiConverterOptionUInt64.write(value.modifiedUnixSeconds, into: &buf)
        FfiConverterUInt64.write(value.probedUnixSeconds, into: &buf)
        FfiConverterString.write(value.logicalSize, into: &buf)
        FfiConverterString.write(value.units, into: &buf)
        FfiConverterSequenceString.write(value.fields, into: &buf)
        FfiConverterSequenceString.write(value.spectralWindows, into: &buf)
        FfiConverterSequenceString.write(value.scans, into: &buf)
        FfiConverterSequenceString.write(value.antennas, into: &buf)
        FfiConverterSequenceString.write(value.correlations, into: &buf)
        FfiConverterSequenceString.write(value.columns, into: &buf)
        FfiConverterSequenceString.write(value.dataColumns, into: &buf)
        FfiConverterSequenceString.write(value.subtables, into: &buf)
        FfiConverterSequenceUInt64.write(value.shape, into: &buf)
        FfiConverterString.write(value.notes, into: &buf)
        FfiConverterSequenceString.write(value.diagnostics, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDatasetProbe_lift(_ buf: RustBuffer) throws -> DatasetProbe {
    return try FfiConverterTypeDatasetProbe.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDatasetProbe_lower(_ value: DatasetProbe) -> RustBuffer {
    return FfiConverterTypeDatasetProbe.lower(value)
}


public struct MeasurementSetPlotRequest {
    public var datasetPath: String
    public var preset: MeasurementSetPlotPreset
    public var field: String?
    public var spectralWindow: String?
    public var correlation: String?
    public var dataColumn: String
    public var width: UInt32
    public var height: UInt32
    public var maxPlotPoints: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(datasetPath: String, preset: MeasurementSetPlotPreset, field: String?, spectralWindow: String?, correlation: String?, dataColumn: String, width: UInt32, height: UInt32, maxPlotPoints: UInt64) {
        self.datasetPath = datasetPath
        self.preset = preset
        self.field = field
        self.spectralWindow = spectralWindow
        self.correlation = correlation
        self.dataColumn = dataColumn
        self.width = width
        self.height = height
        self.maxPlotPoints = maxPlotPoints
    }
}

#if compiler(>=6)
extension MeasurementSetPlotRequest: Sendable {}
#endif


extension MeasurementSetPlotRequest: Equatable, Hashable {
    public static func ==(lhs: MeasurementSetPlotRequest, rhs: MeasurementSetPlotRequest) -> Bool {
        if lhs.datasetPath != rhs.datasetPath {
            return false
        }
        if lhs.preset != rhs.preset {
            return false
        }
        if lhs.field != rhs.field {
            return false
        }
        if lhs.spectralWindow != rhs.spectralWindow {
            return false
        }
        if lhs.correlation != rhs.correlation {
            return false
        }
        if lhs.dataColumn != rhs.dataColumn {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.maxPlotPoints != rhs.maxPlotPoints {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(datasetPath)
        hasher.combine(preset)
        hasher.combine(field)
        hasher.combine(spectralWindow)
        hasher.combine(correlation)
        hasher.combine(dataColumn)
        hasher.combine(width)
        hasher.combine(height)
        hasher.combine(maxPlotPoints)
    }
}

extension MeasurementSetPlotRequest: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMeasurementSetPlotRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MeasurementSetPlotRequest {
        return
            try MeasurementSetPlotRequest(
                datasetPath: FfiConverterString.read(from: &buf),
                preset: FfiConverterTypeMeasurementSetPlotPreset.read(from: &buf),
                field: FfiConverterOptionString.read(from: &buf),
                spectralWindow: FfiConverterOptionString.read(from: &buf),
                correlation: FfiConverterOptionString.read(from: &buf),
                dataColumn: FfiConverterString.read(from: &buf),
                width: FfiConverterUInt32.read(from: &buf),
                height: FfiConverterUInt32.read(from: &buf),
                maxPlotPoints: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MeasurementSetPlotRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.datasetPath, into: &buf)
        FfiConverterTypeMeasurementSetPlotPreset.write(value.preset, into: &buf)
        FfiConverterOptionString.write(value.field, into: &buf)
        FfiConverterOptionString.write(value.spectralWindow, into: &buf)
        FfiConverterOptionString.write(value.correlation, into: &buf)
        FfiConverterString.write(value.dataColumn, into: &buf)
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterUInt64.write(value.maxPlotPoints, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeasurementSetPlotRequest_lift(_ buf: RustBuffer) throws -> MeasurementSetPlotRequest {
    return try FfiConverterTypeMeasurementSetPlotRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeasurementSetPlotRequest_lower(_ value: MeasurementSetPlotRequest) -> RustBuffer {
    return FfiConverterTypeMeasurementSetPlotRequest.lower(value)
}


public struct MeasurementSetPlotResult {
    public var preset: MeasurementSetPlotPreset
    public var presetLabel: String
    public var title: String
    public var summary: String
    public var datasetPath: String
    public var dataColumn: String
    public var selectionSummary: String
    public var xAxis: PlotAxisMetadata
    public var yAxis: PlotAxisMetadata
    public var series: [PlotSeriesMetadata]
    public var sampling: PlotSamplingDiagnostics
    public var render: PlotRenderProvenance
    public var imageBytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(preset: MeasurementSetPlotPreset, presetLabel: String, title: String, summary: String, datasetPath: String, dataColumn: String, selectionSummary: String, xAxis: PlotAxisMetadata, yAxis: PlotAxisMetadata, series: [PlotSeriesMetadata], sampling: PlotSamplingDiagnostics, render: PlotRenderProvenance, imageBytes: Data) {
        self.preset = preset
        self.presetLabel = presetLabel
        self.title = title
        self.summary = summary
        self.datasetPath = datasetPath
        self.dataColumn = dataColumn
        self.selectionSummary = selectionSummary
        self.xAxis = xAxis
        self.yAxis = yAxis
        self.series = series
        self.sampling = sampling
        self.render = render
        self.imageBytes = imageBytes
    }
}

#if compiler(>=6)
extension MeasurementSetPlotResult: Sendable {}
#endif


extension MeasurementSetPlotResult: Equatable, Hashable {
    public static func ==(lhs: MeasurementSetPlotResult, rhs: MeasurementSetPlotResult) -> Bool {
        if lhs.preset != rhs.preset {
            return false
        }
        if lhs.presetLabel != rhs.presetLabel {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.summary != rhs.summary {
            return false
        }
        if lhs.datasetPath != rhs.datasetPath {
            return false
        }
        if lhs.dataColumn != rhs.dataColumn {
            return false
        }
        if lhs.selectionSummary != rhs.selectionSummary {
            return false
        }
        if lhs.xAxis != rhs.xAxis {
            return false
        }
        if lhs.yAxis != rhs.yAxis {
            return false
        }
        if lhs.series != rhs.series {
            return false
        }
        if lhs.sampling != rhs.sampling {
            return false
        }
        if lhs.render != rhs.render {
            return false
        }
        if lhs.imageBytes != rhs.imageBytes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(preset)
        hasher.combine(presetLabel)
        hasher.combine(title)
        hasher.combine(summary)
        hasher.combine(datasetPath)
        hasher.combine(dataColumn)
        hasher.combine(selectionSummary)
        hasher.combine(xAxis)
        hasher.combine(yAxis)
        hasher.combine(series)
        hasher.combine(sampling)
        hasher.combine(render)
        hasher.combine(imageBytes)
    }
}

extension MeasurementSetPlotResult: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMeasurementSetPlotResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MeasurementSetPlotResult {
        return
            try MeasurementSetPlotResult(
                preset: FfiConverterTypeMeasurementSetPlotPreset.read(from: &buf),
                presetLabel: FfiConverterString.read(from: &buf),
                title: FfiConverterString.read(from: &buf),
                summary: FfiConverterString.read(from: &buf),
                datasetPath: FfiConverterString.read(from: &buf),
                dataColumn: FfiConverterString.read(from: &buf),
                selectionSummary: FfiConverterString.read(from: &buf),
                xAxis: FfiConverterTypePlotAxisMetadata.read(from: &buf),
                yAxis: FfiConverterTypePlotAxisMetadata.read(from: &buf),
                series: FfiConverterSequenceTypePlotSeriesMetadata.read(from: &buf),
                sampling: FfiConverterTypePlotSamplingDiagnostics.read(from: &buf),
                render: FfiConverterTypePlotRenderProvenance.read(from: &buf),
                imageBytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: MeasurementSetPlotResult, into buf: inout [UInt8]) {
        FfiConverterTypeMeasurementSetPlotPreset.write(value.preset, into: &buf)
        FfiConverterString.write(value.presetLabel, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.summary, into: &buf)
        FfiConverterString.write(value.datasetPath, into: &buf)
        FfiConverterString.write(value.dataColumn, into: &buf)
        FfiConverterString.write(value.selectionSummary, into: &buf)
        FfiConverterTypePlotAxisMetadata.write(value.xAxis, into: &buf)
        FfiConverterTypePlotAxisMetadata.write(value.yAxis, into: &buf)
        FfiConverterSequenceTypePlotSeriesMetadata.write(value.series, into: &buf)
        FfiConverterTypePlotSamplingDiagnostics.write(value.sampling, into: &buf)
        FfiConverterTypePlotRenderProvenance.write(value.render, into: &buf)
        FfiConverterData.write(value.imageBytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeasurementSetPlotResult_lift(_ buf: RustBuffer) throws -> MeasurementSetPlotResult {
    return try FfiConverterTypeMeasurementSetPlotResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeasurementSetPlotResult_lower(_ value: MeasurementSetPlotResult) -> RustBuffer {
    return FfiConverterTypeMeasurementSetPlotResult.lower(value)
}


public struct PlotAxisMetadata {
    public var id: String
    public var label: String
    public var unit: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, label: String, unit: String) {
        self.id = id
        self.label = label
        self.unit = unit
    }
}

#if compiler(>=6)
extension PlotAxisMetadata: Sendable {}
#endif


extension PlotAxisMetadata: Equatable, Hashable {
    public static func ==(lhs: PlotAxisMetadata, rhs: PlotAxisMetadata) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.label != rhs.label {
            return false
        }
        if lhs.unit != rhs.unit {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(label)
        hasher.combine(unit)
    }
}

extension PlotAxisMetadata: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlotAxisMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlotAxisMetadata {
        return
            try PlotAxisMetadata(
                id: FfiConverterString.read(from: &buf),
                label: FfiConverterString.read(from: &buf),
                unit: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PlotAxisMetadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.unit, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlotAxisMetadata_lift(_ buf: RustBuffer) throws -> PlotAxisMetadata {
    return try FfiConverterTypePlotAxisMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlotAxisMetadata_lower(_ value: PlotAxisMetadata) -> RustBuffer {
    return FfiConverterTypePlotAxisMetadata.lower(value)
}


public struct PlotRenderProvenance {
    public var renderer: String
    public var imageFormat: String
    public var width: UInt32
    public var height: UInt32
    public var source: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(renderer: String, imageFormat: String, width: UInt32, height: UInt32, source: String) {
        self.renderer = renderer
        self.imageFormat = imageFormat
        self.width = width
        self.height = height
        self.source = source
    }
}

#if compiler(>=6)
extension PlotRenderProvenance: Sendable {}
#endif


extension PlotRenderProvenance: Equatable, Hashable {
    public static func ==(lhs: PlotRenderProvenance, rhs: PlotRenderProvenance) -> Bool {
        if lhs.renderer != rhs.renderer {
            return false
        }
        if lhs.imageFormat != rhs.imageFormat {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.source != rhs.source {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(renderer)
        hasher.combine(imageFormat)
        hasher.combine(width)
        hasher.combine(height)
        hasher.combine(source)
    }
}

extension PlotRenderProvenance: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlotRenderProvenance: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlotRenderProvenance {
        return
            try PlotRenderProvenance(
                renderer: FfiConverterString.read(from: &buf),
                imageFormat: FfiConverterString.read(from: &buf),
                width: FfiConverterUInt32.read(from: &buf),
                height: FfiConverterUInt32.read(from: &buf),
                source: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PlotRenderProvenance, into buf: inout [UInt8]) {
        FfiConverterString.write(value.renderer, into: &buf)
        FfiConverterString.write(value.imageFormat, into: &buf)
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterString.write(value.source, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlotRenderProvenance_lift(_ buf: RustBuffer) throws -> PlotRenderProvenance {
    return try FfiConverterTypePlotRenderProvenance.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlotRenderProvenance_lower(_ value: PlotRenderProvenance) -> RustBuffer {
    return FfiConverterTypePlotRenderProvenance.lower(value)
}


public struct PlotSamplingDiagnostics {
    public var requestedMaxPoints: UInt64
    public var renderedPointCount: UInt64
    public var seriesCount: UInt64
    public var diagnostics: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(requestedMaxPoints: UInt64, renderedPointCount: UInt64, seriesCount: UInt64, diagnostics: [String]) {
        self.requestedMaxPoints = requestedMaxPoints
        self.renderedPointCount = renderedPointCount
        self.seriesCount = seriesCount
        self.diagnostics = diagnostics
    }
}

#if compiler(>=6)
extension PlotSamplingDiagnostics: Sendable {}
#endif


extension PlotSamplingDiagnostics: Equatable, Hashable {
    public static func ==(lhs: PlotSamplingDiagnostics, rhs: PlotSamplingDiagnostics) -> Bool {
        if lhs.requestedMaxPoints != rhs.requestedMaxPoints {
            return false
        }
        if lhs.renderedPointCount != rhs.renderedPointCount {
            return false
        }
        if lhs.seriesCount != rhs.seriesCount {
            return false
        }
        if lhs.diagnostics != rhs.diagnostics {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(requestedMaxPoints)
        hasher.combine(renderedPointCount)
        hasher.combine(seriesCount)
        hasher.combine(diagnostics)
    }
}

extension PlotSamplingDiagnostics: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlotSamplingDiagnostics: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlotSamplingDiagnostics {
        return
            try PlotSamplingDiagnostics(
                requestedMaxPoints: FfiConverterUInt64.read(from: &buf),
                renderedPointCount: FfiConverterUInt64.read(from: &buf),
                seriesCount: FfiConverterUInt64.read(from: &buf),
                diagnostics: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: PlotSamplingDiagnostics, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.requestedMaxPoints, into: &buf)
        FfiConverterUInt64.write(value.renderedPointCount, into: &buf)
        FfiConverterUInt64.write(value.seriesCount, into: &buf)
        FfiConverterSequenceString.write(value.diagnostics, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlotSamplingDiagnostics_lift(_ buf: RustBuffer) throws -> PlotSamplingDiagnostics {
    return try FfiConverterTypePlotSamplingDiagnostics.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlotSamplingDiagnostics_lower(_ value: PlotSamplingDiagnostics) -> RustBuffer {
    return FfiConverterTypePlotSamplingDiagnostics.lower(value)
}


public struct PlotSeriesMetadata {
    public var label: String
    public var colorGroup: String
    public var pointCount: UInt64
    public var firstRow: UInt64?
    public var lastRow: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(label: String, colorGroup: String, pointCount: UInt64, firstRow: UInt64?, lastRow: UInt64?) {
        self.label = label
        self.colorGroup = colorGroup
        self.pointCount = pointCount
        self.firstRow = firstRow
        self.lastRow = lastRow
    }
}

#if compiler(>=6)
extension PlotSeriesMetadata: Sendable {}
#endif


extension PlotSeriesMetadata: Equatable, Hashable {
    public static func ==(lhs: PlotSeriesMetadata, rhs: PlotSeriesMetadata) -> Bool {
        if lhs.label != rhs.label {
            return false
        }
        if lhs.colorGroup != rhs.colorGroup {
            return false
        }
        if lhs.pointCount != rhs.pointCount {
            return false
        }
        if lhs.firstRow != rhs.firstRow {
            return false
        }
        if lhs.lastRow != rhs.lastRow {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(label)
        hasher.combine(colorGroup)
        hasher.combine(pointCount)
        hasher.combine(firstRow)
        hasher.combine(lastRow)
    }
}

extension PlotSeriesMetadata: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlotSeriesMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlotSeriesMetadata {
        return
            try PlotSeriesMetadata(
                label: FfiConverterString.read(from: &buf),
                colorGroup: FfiConverterString.read(from: &buf),
                pointCount: FfiConverterUInt64.read(from: &buf),
                firstRow: FfiConverterOptionUInt64.read(from: &buf),
                lastRow: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: PlotSeriesMetadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.colorGroup, into: &buf)
        FfiConverterUInt64.write(value.pointCount, into: &buf)
        FfiConverterOptionUInt64.write(value.firstRow, into: &buf)
        FfiConverterOptionUInt64.write(value.lastRow, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlotSeriesMetadata_lift(_ buf: RustBuffer) throws -> PlotSeriesMetadata {
    return try FfiConverterTypePlotSeriesMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlotSeriesMetadata_lower(_ value: PlotSeriesMetadata) -> RustBuffer {
    return FfiConverterTypePlotSeriesMetadata.lower(value)
}


public struct ProjectProbe {
    public var name: String
    public var rootPath: String
    public var datasets: [DatasetProbe]
    public var diagnostics: [String]
    public var scannedEntryCount: UInt64
    public var truncated: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, rootPath: String, datasets: [DatasetProbe], diagnostics: [String], scannedEntryCount: UInt64, truncated: Bool) {
        self.name = name
        self.rootPath = rootPath
        self.datasets = datasets
        self.diagnostics = diagnostics
        self.scannedEntryCount = scannedEntryCount
        self.truncated = truncated
    }
}

#if compiler(>=6)
extension ProjectProbe: Sendable {}
#endif


extension ProjectProbe: Equatable, Hashable {
    public static func ==(lhs: ProjectProbe, rhs: ProjectProbe) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.rootPath != rhs.rootPath {
            return false
        }
        if lhs.datasets != rhs.datasets {
            return false
        }
        if lhs.diagnostics != rhs.diagnostics {
            return false
        }
        if lhs.scannedEntryCount != rhs.scannedEntryCount {
            return false
        }
        if lhs.truncated != rhs.truncated {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(rootPath)
        hasher.combine(datasets)
        hasher.combine(diagnostics)
        hasher.combine(scannedEntryCount)
        hasher.combine(truncated)
    }
}

extension ProjectProbe: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProjectProbe: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProjectProbe {
        return
            try ProjectProbe(
                name: FfiConverterString.read(from: &buf),
                rootPath: FfiConverterString.read(from: &buf),
                datasets: FfiConverterSequenceTypeDatasetProbe.read(from: &buf),
                diagnostics: FfiConverterSequenceString.read(from: &buf),
                scannedEntryCount: FfiConverterUInt64.read(from: &buf),
                truncated: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ProjectProbe, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.rootPath, into: &buf)
        FfiConverterSequenceTypeDatasetProbe.write(value.datasets, into: &buf)
        FfiConverterSequenceString.write(value.diagnostics, into: &buf)
        FfiConverterUInt64.write(value.scannedEntryCount, into: &buf)
        FfiConverterBool.write(value.truncated, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProjectProbe_lift(_ buf: RustBuffer) throws -> ProjectProbe {
    return try FfiConverterTypeProjectProbe.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProjectProbe_lower(_ value: ProjectProbe) -> RustBuffer {
    return FfiConverterTypeProjectProbe.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DatasetKind {

    case measurementSet
    case image
    case table
}


#if compiler(>=6)
extension DatasetKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDatasetKind: FfiConverterRustBuffer {
    typealias SwiftType = DatasetKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DatasetKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .measurementSet

        case 2: return .image

        case 3: return .table

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DatasetKind, into buf: inout [UInt8]) {
        switch value {


        case .measurementSet:
            writeInt(&buf, Int32(1))


        case .image:
            writeInt(&buf, Int32(2))


        case .table:
            writeInt(&buf, Int32(3))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDatasetKind_lift(_ buf: RustBuffer) throws -> DatasetKind {
    return try FfiConverterTypeDatasetKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDatasetKind_lower(_ value: DatasetKind) -> RustBuffer {
    return FfiConverterTypeDatasetKind.lower(value)
}


extension DatasetKind: Equatable, Hashable {}

extension DatasetKind: Codable {}




extension DatasetKind: CaseIterable {}




public enum FrontendServiceError: Swift.Error {



    case InvalidPath(reason: String
    )
    case Io(reason: String
    )
    case Probe(reason: String
    )
    case Plot(reason: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFrontendServiceError: FfiConverterRustBuffer {
    typealias SwiftType = FrontendServiceError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FrontendServiceError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .InvalidPath(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Io(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Probe(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Plot(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FrontendServiceError, into buf: inout [UInt8]) {
        switch value {





        case let .InvalidPath(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)


        case let .Io(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)


        case let .Probe(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)


        case let .Plot(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrontendServiceError_lift(_ buf: RustBuffer) throws -> FrontendServiceError {
    return try FfiConverterTypeFrontendServiceError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrontendServiceError_lower(_ value: FrontendServiceError) -> RustBuffer {
    return FfiConverterTypeFrontendServiceError.lower(value)
}


extension FrontendServiceError: Equatable, Hashable {}

extension FrontendServiceError: Codable {}




extension FrontendServiceError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MeasurementSetPlotPreset {

    case amplitudeVsFrequency
    case amplitudeVsChannel
    case amplitudeVsUvDistance
    case amplitudeVsTime
}


#if compiler(>=6)
extension MeasurementSetPlotPreset: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMeasurementSetPlotPreset: FfiConverterRustBuffer {
    typealias SwiftType = MeasurementSetPlotPreset

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MeasurementSetPlotPreset {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .amplitudeVsFrequency

        case 2: return .amplitudeVsChannel

        case 3: return .amplitudeVsUvDistance

        case 4: return .amplitudeVsTime

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MeasurementSetPlotPreset, into buf: inout [UInt8]) {
        switch value {


        case .amplitudeVsFrequency:
            writeInt(&buf, Int32(1))


        case .amplitudeVsChannel:
            writeInt(&buf, Int32(2))


        case .amplitudeVsUvDistance:
            writeInt(&buf, Int32(3))


        case .amplitudeVsTime:
            writeInt(&buf, Int32(4))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeasurementSetPlotPreset_lift(_ buf: RustBuffer) throws -> MeasurementSetPlotPreset {
    return try FfiConverterTypeMeasurementSetPlotPreset.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeasurementSetPlotPreset_lower(_ value: MeasurementSetPlotPreset) -> RustBuffer {
    return FfiConverterTypeMeasurementSetPlotPreset.lower(value)
}


extension MeasurementSetPlotPreset: Equatable, Hashable {}

extension MeasurementSetPlotPreset: Codable {}




extension MeasurementSetPlotPreset: CaseIterable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDatasetProbe: FfiConverterRustBuffer {
    typealias SwiftType = DatasetProbe?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDatasetProbe.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDatasetProbe.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt64: FfiConverterRustBuffer {
    typealias SwiftType = [UInt64]

    public static func write(_ value: [UInt64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt64.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt64] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt64.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDatasetProbe: FfiConverterRustBuffer {
    typealias SwiftType = [DatasetProbe]

    public static func write(_ value: [DatasetProbe], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDatasetProbe.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DatasetProbe] {
        let len: Int32 = try readInt(&buf)
        var seq = [DatasetProbe]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDatasetProbe.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePlotSeriesMetadata: FfiConverterRustBuffer {
    typealias SwiftType = [PlotSeriesMetadata]

    public static func write(_ value: [PlotSeriesMetadata], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePlotSeriesMetadata.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PlotSeriesMetadata] {
        let len: Int32 = try readInt(&buf)
        var seq = [PlotSeriesMetadata]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePlotSeriesMetadata.read(from: &buf))
        }
        return seq
    }
}
public func buildMeasurementSetPlot(request: MeasurementSetPlotRequest)throws  -> MeasurementSetPlotResult  {
    return try  FfiConverterTypeMeasurementSetPlotResult_lift(try rustCallWithError(FfiConverterTypeFrontendServiceError_lift) {
    uniffi_casars_frontend_services_fn_func_build_measurement_set_plot(
        FfiConverterTypeMeasurementSetPlotRequest_lower(request),$0
    )
})
}
public func probePath(path: String)throws  -> DatasetProbe?  {
    return try  FfiConverterOptionTypeDatasetProbe.lift(try rustCallWithError(FfiConverterTypeFrontendServiceError_lift) {
    uniffi_casars_frontend_services_fn_func_probe_path(
        FfiConverterString.lower(path),$0
    )
})
}
public func probeProject(path: String)throws  -> ProjectProbe  {
    return try  FfiConverterTypeProjectProbe_lift(try rustCallWithError(FfiConverterTypeFrontendServiceError_lift) {
    uniffi_casars_frontend_services_fn_func_probe_project(
        FfiConverterString.lower(path),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_casars_frontend_services_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_casars_frontend_services_checksum_func_build_measurement_set_plot() != 34309) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_casars_frontend_services_checksum_func_probe_path() != 47483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_casars_frontend_services_checksum_func_probe_project() != 9335) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCasarsFrontendServicesInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all