[casars]
format = 1
surface = "imager"
kind = "task"
contract = 5

[parameters]
vis = "VLASS1.2.sb36484946.eb36542800.58574.4235612037_ptgfix_split_bright_source.ms"
imagename = "products/vlass-all-fields"
imsize = 12150
cell = "0.6arcsec"
datacolumn = "data"
field = "1107~1127,1512~1532,1542~1562"
phasecenter_field = "1525"
spw = "2~17"
channel_start = 0
channel_count = 64
uvrange = "<12km"
intent = "OBSERVE_TARGET#UNSPECIFIED"
stokes = "I"
projection = "SIN"
specmode = "mfs"
interpolation = "linear"
perchanweightdensity = true
weighting = "briggs"
robust = 1.0
gridder = "awproject"
wprojplanes = 32
cfcache = "cf-cache/vlass-spw2-17"
cf_resident_mb = 512
facets = 1
aterm = true
psterm = false
wbawp = true
conjbeams = true
usepointing = true
computepastep = 360.0
rotatepastep = 360.0
pointingoffsetsigdev = "0"
mosweight = false
normtype = "flatnoise"
pblimit = 0.0001
deconvolver = "mtmfs"
nterms = 2
scales = "0,5,12"
smallscalebias = 0.0
restoringbeam = "common"
niter = 0
gain = 0.1
threshold = "0Jy"
nsigma = 5.0
minor_cycle_length = 2000
cyclefactor = 3.0
minpsffraction = 0.05
maxpsffraction = 0.8
usemask = "user"
write_pb = true
pbcor = false
parallel = false
standard_mfs_acceleration = "cpu"
imaging_memory_target_mb = 32768
write_preview_pngs = false
