"""Generated CASA-named wrappers for every catalog task.

Do not edit by hand; run ``scripts/generate-python-parameter-wrappers.py``.
"""

from __future__ import annotations

from collections.abc import Mapping
from os import PathLike
from typing import Literal, TypeAlias

from ..parameters import ParameterData, TaskParameters
from ._runner import TaskCompletion, run as _run

StrPath: TypeAlias = str | PathLike[str]
_UNSET = object()


def _explicit(values: Mapping[str, object], names: tuple[str, ...]) -> dict[str, ParameterData]:
    return {name: values[name] for name in names if values[name] is not _UNSET}  # type: ignore[misc]


def msexplore(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    format: Literal['json', 'text'] | object = _UNSET,
    output: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    selectdata: bool | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    timerange: str | object = _UNSET,
    uvrange: str | object = _UNSET,
    antenna: str | object = _UNSET,
    scan: str | object = _UNSET,
    correlation: str | object = _UNSET,
    observation: str | object = _UNSET,
    array: str | object = _UNSET,
    intent: str | object = _UNSET,
    feed: str | object = _UNSET,
    msselect: str | object = _UNSET,
    page_spec: StrPath | object = _UNSET,
    preset: Literal['amplitude_phase_vs_time_stacked', 'amplitude_vs_channel', 'amplitude_vs_frequency', 'amplitude_vs_time', 'amplitude_vs_uv_distance', 'amplitude_vs_velocity', 'antenna_layout', 'azimuth_vs_elevation', 'azimuth_vs_time', 'elevation_vs_time', 'flag_vs_time', 'flagrow_vs_time', 'hour_angle_vs_time', 'none', 'parallactic_angle_vs_time', 'phase_vs_channel', 'phase_vs_frequency', 'phase_vs_time', 'phase_vs_velocity', 'real_vs_imaginary', 'scan_timeline', 'sigma_spectrum_vs_time', 'sigma_vs_time', 'spectral_window_coverage', 'uv_coverage', 'weight_spectrum_vs_time', 'weight_vs_time'] | object = _UNSET,
    x_axis: str | object = _UNSET,
    y_axis: str | object = _UNSET,
    y_axis2: str | object = _UNSET,
    datacolumn: str | object = _UNSET,
    color_by: Literal['baseline', 'correlation', 'field', 'none', 'scan', 'spw'] | object = _UNSET,
    avgchannel: int | Literal['none'] | object = _UNSET,
    avgtime: float | Literal['none'] | object = _UNSET,
    avgscan: bool | object = _UNSET,
    avgfield: bool | object = _UNSET,
    avgbaseline: bool | object = _UNSET,
    avgantenna: bool | object = _UNSET,
    avgspw: bool | object = _UNSET,
    scalar: bool | object = _UNSET,
    freqframe: Literal['BARY', 'CMB', 'GALACTO', 'GEO', 'LGROUP', 'LSRD', 'LSRK', 'TOPO', 'none'] | object = _UNSET,
    restfreq: str | object = _UNSET,
    veldef: Literal['OPTICAL', 'RADIO', 'TRUE'] | object = _UNSET,
    iteraxis: Literal['correlation', 'field', 'none', 'scan', 'spw'] | object = _UNSET,
    gridrows: int | object = _UNSET,
    gridcols: int | object = _UNSET,
    xselfscale: bool | object = _UNSET,
    yselfscale: bool | object = _UNSET,
    xsharedaxis: bool | object = _UNSET,
    ysharedaxis: bool | object = _UNSET,
    title: str | object = _UNSET,
    xlabel: str | object = _UNSET,
    ylabel: str | object = _UNSET,
    symbol_size: float | Literal['none'] | object = _UNSET,
    showlegend: bool | object = _UNSET,
    legendposition: Literal['exteriorBottom', 'exteriorLeft', 'exteriorRight', 'exteriorTop', 'lowerLeft', 'lowerRight', 'upperLeft', 'upperRight'] | object = _UNSET,
    showmajorgrid: bool | object = _UNSET,
    showminorgrid: bool | object = _UNSET,
    headeritems: str | object = _UNSET,
    max_points: int | object = _UNSET,
    plot_output: StrPath | object = _UNSET,
    plot_format: Literal['pdf', 'png', 'txt'] | object = _UNSET,
    plot_width: int | object = _UNSET,
    plot_height: int | object = _UNSET,
    flag_action: Literal['flag', 'none', 'unflag'] | object = _UNSET,
    flag_xmin: float | Literal['none'] | object = _UNSET,
    flag_xmax: float | Literal['none'] | object = _UNSET,
    flag_ymin: float | Literal['none'] | object = _UNSET,
    flag_ymax: float | Literal['none'] | object = _UNSET,
    flag_plotindex: int | Literal['none'] | object = _UNSET,
    flag_panel: str | object = _UNSET,
    flag_extcorr: bool | object = _UNSET,
    flag_extchannel: bool | object = _UNSET,
    flag_selected: bool | object = _UNSET,
    flag_apply: bool | object = _UNSET,
    flag_output: StrPath | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """explore and export common MeasurementSet plotms-style plots"""
    overrides = _explicit(locals(), ('vis', 'format', 'output', 'overwrite', 'selectdata', 'field', 'spw', 'timerange', 'uvrange', 'antenna', 'scan', 'correlation', 'observation', 'array', 'intent', 'feed', 'msselect', 'page_spec', 'preset', 'x_axis', 'y_axis', 'y_axis2', 'datacolumn', 'color_by', 'avgchannel', 'avgtime', 'avgscan', 'avgfield', 'avgbaseline', 'avgantenna', 'avgspw', 'scalar', 'freqframe', 'restfreq', 'veldef', 'iteraxis', 'gridrows', 'gridcols', 'xselfscale', 'yselfscale', 'xsharedaxis', 'ysharedaxis', 'title', 'xlabel', 'ylabel', 'symbol_size', 'showlegend', 'legendposition', 'showmajorgrid', 'showminorgrid', 'headeritems', 'max_points', 'plot_output', 'plot_format', 'plot_width', 'plot_height', 'flag_action', 'flag_xmin', 'flag_xmax', 'flag_ymin', 'flag_ymax', 'flag_plotindex', 'flag_panel', 'flag_extcorr', 'flag_extchannel', 'flag_selected', 'flag_apply', 'flag_output'))
    return _run(
        "msexplore",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def calibrate(
    *,
    mode: Literal['apply', 'continuum_subtract', 'export_corrected_data', 'fluxscale', 'gencal', 'solve_bandpass', 'solve_gain', 'stats', 'summary'] | object = _UNSET,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    outputvis: StrPath | object = _UNSET,
    summary_paths: str | object = _UNSET,
    gaintables: str | object = _UNSET,
    table_path: StrPath | object = _UNSET,
    callib: StrPath | object = _UNSET,
    gainfield: str | object = _UNSET,
    interp: str | object = _UNSET,
    spwmap: str | object = _UNSET,
    apply_mode: Literal['calflag', 'calonly', 'trial'] | object = _UNSET,
    calwt: str | object = _UNSET,
    output: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parang: bool | object = _UNSET,
    format: Literal['json', 'text'] | object = _UNSET,
    stats_axis: Literal['amp', 'imag', 'phase', 'real'] | object = _UNSET,
    stats_datacolumn: str | object = _UNSET,
    fit_spw: str | object = _UNSET,
    use_flags: bool | object = _UNSET,
    fit_order: int | object = _UNSET,
    out_table: StrPath | object = _UNSET,
    refant: str | object = _UNSET,
    gain_type: Literal['g', 't'] | object = _UNSET,
    solve_mode: Literal['ap', 'p'] | object = _UNSET,
    solint: str | object = _UNSET,
    gain_combine: str | object = _UNSET,
    gain_model_source: Literal['model-column', 'point'] | object = _UNSET,
    smodel: str | object = _UNSET,
    min_snr: float | object = _UNSET,
    bandpass_combine: Literal['field', 'none', 'scan', 'scan,field'] | object = _UNSET,
    bandtype: Literal['b', 'bpoly'] | object = _UNSET,
    solnorm: bool | object = _UNSET,
    fluxscale_input: StrPath | object = _UNSET,
    reference_fields: str | object = _UNSET,
    transfer_fields: str | object = _UNSET,
    refspwmap: str | object = _UNSET,
    gainthreshold: float | Literal['none'] | object = _UNSET,
    incremental: bool | object = _UNSET,
    selectdata: bool | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    antenna: str | object = _UNSET,
    scan: str | object = _UNSET,
    observation: str | object = _UNSET,
    array: str | object = _UNSET,
    timerange: str | object = _UNSET,
    msselect: str | object = _UNSET,
    caltype: Literal['antpos', 'gceff', 'opac'] | Literal['none'] | object = _UNSET,
    parameter: str | object = _UNSET,
    gaincurve_table: StrPath | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """apply, inspect, and solve CASA-style calibration workflows"""
    overrides = _explicit(locals(), ('mode', 'vis', 'outputvis', 'summary_paths', 'gaintables', 'table_path', 'callib', 'gainfield', 'interp', 'spwmap', 'apply_mode', 'calwt', 'output', 'overwrite', 'parang', 'format', 'stats_axis', 'stats_datacolumn', 'fit_spw', 'use_flags', 'fit_order', 'out_table', 'refant', 'gain_type', 'solve_mode', 'solint', 'gain_combine', 'gain_model_source', 'smodel', 'min_snr', 'bandpass_combine', 'bandtype', 'solnorm', 'fluxscale_input', 'reference_fields', 'transfer_fields', 'refspwmap', 'gainthreshold', 'incremental', 'selectdata', 'field', 'spw', 'antenna', 'scan', 'observation', 'array', 'timerange', 'msselect', 'caltype', 'parameter', 'gaincurve_table'))
    return _run(
        "calibrate",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def importvla(
    *,
    archivefiles: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    bandname: Literal['4', 'C', 'K', 'Ka', 'L', 'P', 'Q', 'S', 'U', 'X', 'none'] | object = _UNSET,
    frequencytol: str | object = _UNSET,
    project: str | object = _UNSET,
    starttime: str | object = _UNSET,
    stoptime: str | object = _UNSET,
    applytsys: bool | object = _UNSET,
    autocorr: bool | object = _UNSET,
    antnamescheme: Literal['new', 'old'] | object = _UNSET,
    keepblanks: bool | object = _UNSET,
    evlabands: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """scan or import old VLA export archives from disk"""
    overrides = _explicit(locals(), ('archivefiles', 'vis', 'bandname', 'frequencytol', 'project', 'starttime', 'stoptime', 'applytsys', 'autocorr', 'antnamescheme', 'keepblanks', 'evlabands'))
    return _run(
        "importvla",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def imager(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    imagename: StrPath | object = _UNSET,
    imsize: int | list[int] | tuple[int, ...] | Literal['auto'] | object = _UNSET,
    cell: str | list[str] | tuple[str, ...] | object = _UNSET,
    datacolumn: str | object = _UNSET,
    savemodel: Literal['modelcolumn', 'none'] | object = _UNSET,
    startmodel: StrPath | object = _UNSET,
    outlierfile: StrPath | object = _UNSET,
    field: str | object = _UNSET,
    phasecenter_field: str | object = _UNSET,
    ddid: str | object = _UNSET,
    phasecenter: str | object = _UNSET,
    spw: str | object = _UNSET,
    channel_start: int | Literal['none'] | object = _UNSET,
    channel_count: int | Literal['none'] | object = _UNSET,
    polarization: Literal['I', 'LL', 'Q', 'RR', 'U', 'V', 'XX', 'YY'] | object = _UNSET,
    specmode: Literal['cube', 'cubedata', 'mfs'] | object = _UNSET,
    start: str | object = _UNSET,
    width: int | Literal['none'] | object = _UNSET,
    outframe: Literal['BARY', 'CMB', 'GALACTO', 'GEO', 'LGROUP', 'LSRD', 'LSRK', 'REST', 'TOPO', 'none'] | object = _UNSET,
    veltype: Literal['BETA', 'GAMMA', 'OPTICAL', 'RADIO', 'TRUE', 'none'] | object = _UNSET,
    interpolation: Literal['cubic', 'linear', 'nearest', 'none'] | object = _UNSET,
    restfreq: str | object = _UNSET,
    restoringbeam: Literal['common', 'none'] | object = _UNSET,
    perchanweightdensity: bool | object = _UNSET,
    dirty_only: bool | object = _UNSET,
    niter: int | object = _UNSET,
    threshold: str | object = _UNSET,
    nmajor: int | object = _UNSET,
    fullsummary: bool | object = _UNSET,
    gain: float | object = _UNSET,
    nsigma: float | object = _UNSET,
    psfcutoff: float | object = _UNSET,
    minor_cycle_length: int | object = _UNSET,
    cyclefactor: float | object = _UNSET,
    deconvolver: Literal['clark', 'hogbom', 'mtmfs', 'multiscale'] | object = _UNSET,
    minpsffraction: float | object = _UNSET,
    maxpsffraction: float | object = _UNSET,
    nterms: int | object = _UNSET,
    hogbom_iteration_mode: str | object = _UNSET,
    scales: str | object = _UNSET,
    smallscalebias: float | object = _UNSET,
    usemask: Literal['auto-multithresh', 'user'] | object = _UNSET,
    sidelobethreshold: float | object = _UNSET,
    noisethreshold: float | object = _UNSET,
    lownoisethreshold: float | object = _UNSET,
    negativethreshold: float | object = _UNSET,
    minbeamfrac: float | object = _UNSET,
    growiterations: int | object = _UNSET,
    mask_box: str | object = _UNSET,
    weighting: Literal['briggs', 'briggsbwtaper', 'natural', 'uniform'] | object = _UNSET,
    mask_image: StrPath | object = _UNSET,
    robust: float | object = _UNSET,
    wprojplanes: int | Literal['none'] | object = _UNSET,
    usepointing: bool | object = _UNSET,
    uvtaper: str | object = _UNSET,
    write_preview_pngs: bool | object = _UNSET,
    write_pb: bool | object = _UNSET,
    pbcor: bool | object = _UNSET,
    pblimit: float | object = _UNSET,
    wterm: Literal['direct', 'none', 'wproject'] | object = _UNSET,
    gridder: Literal['awp2', 'awphpg', 'awproject', 'mosaic', 'standard', 'widefield', 'wproject'] | object = _UNSET,
    standard_mfs_acceleration: Literal['auto', 'cpu', 'metal', 'multi-cpu'] | object = _UNSET,
    parallel: bool | Literal['none'] | object = _UNSET,
    imaging_read_ahead_blocks: int | Literal['none'] | object = _UNSET,
    imaging_fft_backend: Literal['accelerate', 'auto', 'metal-mpsgraph', 'rustfft'] | object = _UNSET,
    chanchunks: int | Literal['none'] | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Run CASA-compatible dirty and deconvolved imaging from a MeasurementSet"""
    overrides = _explicit(locals(), ('vis', 'imagename', 'imsize', 'cell', 'datacolumn', 'savemodel', 'startmodel', 'outlierfile', 'field', 'phasecenter_field', 'ddid', 'phasecenter', 'spw', 'channel_start', 'channel_count', 'polarization', 'specmode', 'start', 'width', 'outframe', 'veltype', 'interpolation', 'restfreq', 'restoringbeam', 'perchanweightdensity', 'dirty_only', 'niter', 'threshold', 'nmajor', 'fullsummary', 'gain', 'nsigma', 'psfcutoff', 'minor_cycle_length', 'cyclefactor', 'deconvolver', 'minpsffraction', 'maxpsffraction', 'nterms', 'hogbom_iteration_mode', 'scales', 'smallscalebias', 'usemask', 'sidelobethreshold', 'noisethreshold', 'lownoisethreshold', 'negativethreshold', 'minbeamfrac', 'growiterations', 'mask_box', 'weighting', 'mask_image', 'robust', 'wprojplanes', 'usepointing', 'uvtaper', 'write_preview_pngs', 'write_pb', 'pbcor', 'pblimit', 'wterm', 'gridder', 'standard_mfs_acceleration', 'parallel', 'imaging_read_ahead_blocks', 'imaging_fft_backend', 'chanchunks'))
    return _run(
        "imager",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def simobserve(
    *,
    request_kind: Literal['family', 'run'] | object = _UNSET,
    model: StrPath | object = _UNSET,
    out: StrPath | object = _UNSET,
    inbright: str | object = _UNSET,
    duration: float | object = _UNSET,
    integration: str | object = _UNSET,
    start_frequency_hz: float | object = _UNSET,
    channel_width_hz: float | object = _UNSET,
    channel_count: int | Literal['none'] | object = _UNSET,
    overwrite: bool | object = _UNSET,
    predict_model: bool | object = _UNSET,
    polarizations: str | object = _UNSET,
    polarization_basis: str | object = _UNSET,
    worker_policy: Literal['auto', 'fixed'] | object = _UNSET,
    row_workers: int | Literal['none'] | object = _UNSET,
    channel_workers: int | Literal['none'] | object = _UNSET,
    corruption_seed: str | object = _UNSET,
    noise_simplenoise_jy: float | Literal['none'] | object = _UNSET,
    gain_mode: str | object = _UNSET,
    gain_interval_seconds: float | object = _UNSET,
    gain_amplitude: str | object = _UNSET,
    bandpass_mode: str | object = _UNSET,
    bandpass_interval_seconds: float | object = _UNSET,
    bandpass_amplitude: str | object = _UNSET,
    leakage_amplitude: str | object = _UNSET,
    leakage_offset: str | object = _UNSET,
    pointing_offset_ra_arcsec: float | Literal['none'] | object = _UNSET,
    pointing_offset_dec_arcsec: float | Literal['none'] | object = _UNSET,
    source_model: str | object = _UNSET,
    telescope: Literal['ACA', 'ALMA', 'VLA'] | object = _UNSET,
    array_config: Literal['A', 'aca.cycle10.cfg', 'alma.cycle10.5.cfg', 'synthetic-aca', 'synthetic-alma-compact', 'synthetic-simalma', 'synthetic-vla-d', 'vla.b.cfg', 'vla.c.cfg', 'vla.d.cfg'] | object = _UNSET,
    band: Literal['Band 3', 'Band 6', 'Band 7', 'Band 9', 'C', 'K', 'Ka', 'Ku', 'L', 'Q', 'S', 'X'] | object = _UNSET,
    target_ms_size_gib: float | object = _UNSET,
    output_ms: StrPath | object = _UNSET,
    ms_channels: int | object = _UNSET,
    image_channels: int | object = _UNSET,
    pointing_count: int | object = _UNSET,
    time_sample_count: int | Literal['none'] | object = _UNSET,
    integration_seconds: float | Literal['none'] | object = _UNSET,
    start_time_mjd_seconds: float | Literal['none'] | object = _UNSET,
    imaging_mode: Literal['aca', 'continuum', 'continuum_mfs', 'cube', 'cubedata', 'mfs', 'mosaic', 'mosaic_mfs', 'mt_mfs', 'simalma', 'single_field', 'spectral_cube'] | object = _UNSET,
    observation_mode: Literal['interferometric', 'total_power'] | object = _UNSET,
    measure_actual_size: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Generate a CASA-compatible synthetic VLA MeasurementSet"""
    overrides = _explicit(locals(), ('request_kind', 'model', 'out', 'inbright', 'duration', 'integration', 'start_frequency_hz', 'channel_width_hz', 'channel_count', 'overwrite', 'predict_model', 'polarizations', 'polarization_basis', 'worker_policy', 'row_workers', 'channel_workers', 'corruption_seed', 'noise_simplenoise_jy', 'gain_mode', 'gain_interval_seconds', 'gain_amplitude', 'bandpass_mode', 'bandpass_interval_seconds', 'bandpass_amplitude', 'leakage_amplitude', 'leakage_offset', 'pointing_offset_ra_arcsec', 'pointing_offset_dec_arcsec', 'source_model', 'telescope', 'array_config', 'band', 'target_ms_size_gib', 'output_ms', 'ms_channels', 'image_channels', 'pointing_count', 'time_sample_count', 'integration_seconds', 'start_time_mjd_seconds', 'imaging_mode', 'observation_mode', 'measure_actual_size'))
    return _run(
        "simobserve",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def imhead(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    mode: Literal['list', 'put', 'summary'] | object = _UNSET,
    hdkey: str | object = _UNSET,
    hdvalue: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Inspect or update CASA image header metadata."""
    overrides = _explicit(locals(), ('imagename', 'mode', 'hdkey', 'hdvalue'))
    return _run(
        "imhead",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def imstat(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    box: str | object = _UNSET,
    region: str | object = _UNSET,
    chans: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Compute CASA image statistics over optional pixel, region, and channel selections."""
    overrides = _explicit(locals(), ('imagename', 'box', 'region', 'chans'))
    return _run(
        "imstat",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def immoments(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    outfile: StrPath | object = _UNSET,
    moments: Literal['-1', '0', '1', '2', '3'] | object = _UNSET,
    chans: str | object = _UNSET,
    includepix: str | object = _UNSET,
    mask: str | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Create CASA-style image moment maps"""
    overrides = _explicit(locals(), ('imagename', 'outfile', 'moments', 'chans', 'includepix', 'mask', 'overwrite'))
    return _run(
        "immoments",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def exportfits(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    fitsimage: StrPath | object = _UNSET,
    velocity: bool | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Export CASA images to FITS"""
    overrides = _explicit(locals(), ('imagename', 'fitsimage', 'velocity', 'overwrite'))
    return _run(
        "exportfits",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def mstransform(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    outputvis: StrPath | object = _UNSET,
    spw: str | object = _UNSET,
    width: int | object = _UNSET,
    field: str | object = _UNSET,
    scan: str | object = _UNSET,
    antenna: str | object = _UNSET,
    timerange: str | object = _UNSET,
    msselect: str | object = _UNSET,
    datacolumn: str | object = _UNSET,
    keepflags: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Materialize a selected MeasurementSet into a new output MS."""
    overrides = _explicit(locals(), ('vis', 'outputvis', 'spw', 'width', 'field', 'scan', 'antenna', 'timerange', 'msselect', 'datacolumn', 'keepflags'))
    return _run(
        "mstransform",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def split(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    outputvis: StrPath | object = _UNSET,
    spw: str | object = _UNSET,
    width: int | object = _UNSET,
    field: str | object = _UNSET,
    scan: str | object = _UNSET,
    antenna: str | object = _UNSET,
    timerange: str | object = _UNSET,
    msselect: str | object = _UNSET,
    datacolumn: str | object = _UNSET,
    keepflags: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Create a selected MeasurementSet subset, equivalent to CASA split."""
    overrides = _explicit(locals(), ('vis', 'outputvis', 'spw', 'width', 'field', 'scan', 'antenna', 'timerange', 'msselect', 'datacolumn', 'keepflags'))
    return _run(
        "split",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def uvcontsub(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    outputvis: StrPath | object = _UNSET,
    output: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    format: Literal['json', 'text'] | object = _UNSET,
    stats_datacolumn: str | object = _UNSET,
    fit_spw: str | object = _UNSET,
    fit_order: int | object = _UNSET,
    selectdata: bool | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    antenna: str | object = _UNSET,
    scan: str | object = _UNSET,
    observation: str | object = _UNSET,
    array: str | object = _UNSET,
    timerange: str | object = _UNSET,
    msselect: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Subtract continuum emission from a MeasurementSet."""
    overrides = _explicit(locals(), ('vis', 'outputvis', 'output', 'overwrite', 'format', 'stats_datacolumn', 'fit_spw', 'fit_order', 'selectdata', 'field', 'spw', 'antenna', 'scan', 'observation', 'array', 'timerange', 'msselect'))
    return _run(
        "uvcontsub",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def applycal(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    gaintables: str | object = _UNSET,
    callib: StrPath | object = _UNSET,
    gainfield: str | object = _UNSET,
    interp: str | object = _UNSET,
    spwmap: str | object = _UNSET,
    apply_mode: Literal['calflag', 'calonly', 'trial'] | object = _UNSET,
    calwt: str | object = _UNSET,
    output: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parang: bool | object = _UNSET,
    format: Literal['json', 'text'] | object = _UNSET,
    selectdata: bool | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    antenna: str | object = _UNSET,
    scan: str | object = _UNSET,
    observation: str | object = _UNSET,
    array: str | object = _UNSET,
    timerange: str | object = _UNSET,
    msselect: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Apply one or more calibration tables to a MeasurementSet."""
    overrides = _explicit(locals(), ('vis', 'gaintables', 'callib', 'gainfield', 'interp', 'spwmap', 'apply_mode', 'calwt', 'output', 'overwrite', 'parang', 'format', 'selectdata', 'field', 'spw', 'antenna', 'scan', 'observation', 'array', 'timerange', 'msselect'))
    return _run(
        "applycal",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def gaincal(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    gaintables: str | object = _UNSET,
    callib: StrPath | object = _UNSET,
    gainfield: str | object = _UNSET,
    interp: str | object = _UNSET,
    spwmap: str | object = _UNSET,
    output: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    format: Literal['json', 'text'] | object = _UNSET,
    out_table: StrPath | object = _UNSET,
    refant: str | object = _UNSET,
    gain_type: Literal['g', 't'] | object = _UNSET,
    solve_mode: Literal['ap', 'p'] | object = _UNSET,
    solint: str | object = _UNSET,
    gain_combine: str | object = _UNSET,
    gain_model_source: Literal['model-column', 'point'] | object = _UNSET,
    smodel: str | object = _UNSET,
    min_snr: float | object = _UNSET,
    solnorm: bool | object = _UNSET,
    selectdata: bool | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    antenna: str | object = _UNSET,
    scan: str | object = _UNSET,
    observation: str | object = _UNSET,
    array: str | object = _UNSET,
    timerange: str | object = _UNSET,
    msselect: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Solve antenna gain calibration for a MeasurementSet."""
    overrides = _explicit(locals(), ('vis', 'gaintables', 'callib', 'gainfield', 'interp', 'spwmap', 'output', 'overwrite', 'format', 'out_table', 'refant', 'gain_type', 'solve_mode', 'solint', 'gain_combine', 'gain_model_source', 'smodel', 'min_snr', 'solnorm', 'selectdata', 'field', 'spw', 'antenna', 'scan', 'observation', 'array', 'timerange', 'msselect'))
    return _run(
        "gaincal",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def bandpass(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    gaintables: str | object = _UNSET,
    callib: StrPath | object = _UNSET,
    gainfield: str | object = _UNSET,
    interp: str | object = _UNSET,
    spwmap: str | object = _UNSET,
    output: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    format: Literal['json', 'text'] | object = _UNSET,
    out_table: StrPath | object = _UNSET,
    refant: str | object = _UNSET,
    smodel: str | object = _UNSET,
    min_snr: float | object = _UNSET,
    bandpass_combine: Literal['field', 'none', 'scan', 'scan,field'] | object = _UNSET,
    bandtype: Literal['b', 'bpoly'] | object = _UNSET,
    solnorm: bool | object = _UNSET,
    selectdata: bool | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    antenna: str | object = _UNSET,
    scan: str | object = _UNSET,
    observation: str | object = _UNSET,
    array: str | object = _UNSET,
    timerange: str | object = _UNSET,
    msselect: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Solve bandpass calibration for a MeasurementSet."""
    overrides = _explicit(locals(), ('vis', 'gaintables', 'callib', 'gainfield', 'interp', 'spwmap', 'output', 'overwrite', 'format', 'out_table', 'refant', 'smodel', 'min_snr', 'bandpass_combine', 'bandtype', 'solnorm', 'selectdata', 'field', 'spw', 'antenna', 'scan', 'observation', 'array', 'timerange', 'msselect'))
    return _run(
        "bandpass",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def fluxscale(
    *,
    output: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    format: Literal['json', 'text'] | object = _UNSET,
    out_table: StrPath | object = _UNSET,
    fluxscale_input: StrPath | object = _UNSET,
    reference_fields: str | object = _UNSET,
    transfer_fields: str | object = _UNSET,
    refspwmap: str | object = _UNSET,
    gainthreshold: float | Literal['none'] | object = _UNSET,
    incremental: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Scale gain solutions using reference calibrator fields."""
    overrides = _explicit(locals(), ('output', 'overwrite', 'format', 'out_table', 'fluxscale_input', 'reference_fields', 'transfer_fields', 'refspwmap', 'gainthreshold', 'incremental'))
    return _run(
        "fluxscale",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def gencal(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    output: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    format: Literal['json', 'text'] | object = _UNSET,
    out_table: StrPath | object = _UNSET,
    caltype: Literal['antpos', 'gceff', 'opac'] | Literal['none'] | object = _UNSET,
    parameter: str | object = _UNSET,
    gaincurve_table: StrPath | object = _UNSET,
    spw: str | object = _UNSET,
    antenna: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Generate a calibration table such as antpos, gceff, or opac."""
    overrides = _explicit(locals(), ('vis', 'output', 'overwrite', 'format', 'out_table', 'caltype', 'parameter', 'gaincurve_table', 'spw', 'antenna'))
    return _run(
        "gencal",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def plotms(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    format: Literal['json', 'text'] | object = _UNSET,
    output: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    selectdata: bool | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    timerange: str | object = _UNSET,
    uvrange: str | object = _UNSET,
    antenna: str | object = _UNSET,
    scan: str | object = _UNSET,
    correlation: str | object = _UNSET,
    observation: str | object = _UNSET,
    array: str | object = _UNSET,
    intent: str | object = _UNSET,
    feed: str | object = _UNSET,
    msselect: str | object = _UNSET,
    page_spec: StrPath | object = _UNSET,
    preset: Literal['amplitude_phase_vs_time_stacked', 'amplitude_vs_channel', 'amplitude_vs_frequency', 'amplitude_vs_time', 'amplitude_vs_uv_distance', 'amplitude_vs_velocity', 'antenna_layout', 'azimuth_vs_elevation', 'azimuth_vs_time', 'elevation_vs_time', 'flag_vs_time', 'flagrow_vs_time', 'hour_angle_vs_time', 'none', 'parallactic_angle_vs_time', 'phase_vs_channel', 'phase_vs_frequency', 'phase_vs_time', 'phase_vs_velocity', 'real_vs_imaginary', 'scan_timeline', 'sigma_spectrum_vs_time', 'sigma_vs_time', 'spectral_window_coverage', 'uv_coverage', 'weight_spectrum_vs_time', 'weight_vs_time'] | object = _UNSET,
    x_axis: str | object = _UNSET,
    y_axis: str | object = _UNSET,
    y_axis2: str | object = _UNSET,
    datacolumn: str | object = _UNSET,
    color_by: Literal['baseline', 'correlation', 'field', 'none', 'scan', 'spw'] | object = _UNSET,
    avgchannel: int | Literal['none'] | object = _UNSET,
    avgtime: float | Literal['none'] | object = _UNSET,
    avgscan: bool | object = _UNSET,
    avgfield: bool | object = _UNSET,
    avgbaseline: bool | object = _UNSET,
    avgantenna: bool | object = _UNSET,
    avgspw: bool | object = _UNSET,
    scalar: bool | object = _UNSET,
    freqframe: Literal['BARY', 'CMB', 'GALACTO', 'GEO', 'LGROUP', 'LSRD', 'LSRK', 'TOPO', 'none'] | object = _UNSET,
    restfreq: str | object = _UNSET,
    veldef: Literal['OPTICAL', 'RADIO', 'TRUE'] | object = _UNSET,
    iteraxis: Literal['correlation', 'field', 'none', 'scan', 'spw'] | object = _UNSET,
    gridrows: int | object = _UNSET,
    gridcols: int | object = _UNSET,
    xselfscale: bool | object = _UNSET,
    yselfscale: bool | object = _UNSET,
    xsharedaxis: bool | object = _UNSET,
    ysharedaxis: bool | object = _UNSET,
    title: str | object = _UNSET,
    xlabel: str | object = _UNSET,
    ylabel: str | object = _UNSET,
    symbol_size: float | Literal['none'] | object = _UNSET,
    showlegend: bool | object = _UNSET,
    legendposition: Literal['exteriorBottom', 'exteriorLeft', 'exteriorRight', 'exteriorTop', 'lowerLeft', 'lowerRight', 'upperLeft', 'upperRight'] | object = _UNSET,
    showmajorgrid: bool | object = _UNSET,
    showminorgrid: bool | object = _UNSET,
    headeritems: str | object = _UNSET,
    max_points: int | object = _UNSET,
    plot_output: StrPath | object = _UNSET,
    plot_format: Literal['pdf', 'png', 'txt'] | object = _UNSET,
    plot_width: int | object = _UNSET,
    plot_height: int | object = _UNSET,
    flag_action: Literal['flag', 'none', 'unflag'] | object = _UNSET,
    flag_xmin: float | Literal['none'] | object = _UNSET,
    flag_xmax: float | Literal['none'] | object = _UNSET,
    flag_ymin: float | Literal['none'] | object = _UNSET,
    flag_ymax: float | Literal['none'] | object = _UNSET,
    flag_plotindex: int | Literal['none'] | object = _UNSET,
    flag_panel: str | object = _UNSET,
    flag_extcorr: bool | object = _UNSET,
    flag_extchannel: bool | object = _UNSET,
    flag_selected: bool | object = _UNSET,
    flag_apply: bool | object = _UNSET,
    flag_output: StrPath | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Plot MeasurementSet visibility data with CASA plotms-style selections and axes."""
    overrides = _explicit(locals(), ('vis', 'format', 'output', 'overwrite', 'selectdata', 'field', 'spw', 'timerange', 'uvrange', 'antenna', 'scan', 'correlation', 'observation', 'array', 'intent', 'feed', 'msselect', 'page_spec', 'preset', 'x_axis', 'y_axis', 'y_axis2', 'datacolumn', 'color_by', 'avgchannel', 'avgtime', 'avgscan', 'avgfield', 'avgbaseline', 'avgantenna', 'avgspw', 'scalar', 'freqframe', 'restfreq', 'veldef', 'iteraxis', 'gridrows', 'gridcols', 'xselfscale', 'yselfscale', 'xsharedaxis', 'ysharedaxis', 'title', 'xlabel', 'ylabel', 'symbol_size', 'showlegend', 'legendposition', 'showmajorgrid', 'showminorgrid', 'headeritems', 'max_points', 'plot_output', 'plot_format', 'plot_width', 'plot_height', 'flag_action', 'flag_xmin', 'flag_xmax', 'flag_ymin', 'flag_ymax', 'flag_plotindex', 'flag_panel', 'flag_extcorr', 'flag_extchannel', 'flag_selected', 'flag_apply', 'flag_output'))
    return _run(
        "plotms",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def plotcal(
    *,
    caltable: StrPath | object = _UNSET,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    preset: Literal['bandpass_amplitude_vs_frequency', 'bandpass_phase_vs_frequency', 'corrected_amplitude_vs_frequency', 'corrected_amplitude_vs_time', 'corrected_phase_vs_frequency', 'corrected_phase_vs_time', 'gain_amplitude_vs_time', 'gain_phase_vs_time'] | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    timerange: str | object = _UNSET,
    uvrange: str | object = _UNSET,
    antenna: str | object = _UNSET,
    scan: str | object = _UNSET,
    correlation: str | object = _UNSET,
    observation: str | object = _UNSET,
    array: str | object = _UNSET,
    intent: str | object = _UNSET,
    feed: str | object = _UNSET,
    msselect: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Plot calibration tables and corrected-data diagnostics."""
    overrides = _explicit(locals(), ('caltable', 'vis', 'preset', 'field', 'spw', 'timerange', 'uvrange', 'antenna', 'scan', 'correlation', 'observation', 'array', 'intent', 'feed', 'msselect'))
    return _run(
        "plotcal",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def flagdata(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    mode: Literal['clip', 'extend', 'manual', 'quack', 'rflag', 'summary', 'tfcrop'] | object = _UNSET,
    spw: str | object = _UNSET,
    field: str | object = _UNSET,
    scan: str | object = _UNSET,
    antenna: str | object = _UNSET,
    datacolumn: str | object = _UNSET,
    action: Literal['flag', 'unflag'] | object = _UNSET,
    flagbackup: bool | object = _UNSET,
    clipzeros: bool | object = _UNSET,
    quackinterval: float | object = _UNSET,
    quackmode: Literal['beg', 'end'] | object = _UNSET,
    timecutoff: float | object = _UNSET,
    freqcutoff: float | object = _UNSET,
    timedev: float | Literal['none'] | object = _UNSET,
    freqdev: float | Literal['none'] | object = _UNSET,
    extendflags: bool | object = _UNSET,
    extendpols: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Run native CASA-style MeasurementSet flagging."""
    overrides = _explicit(locals(), ('vis', 'mode', 'spw', 'field', 'scan', 'antenna', 'datacolumn', 'action', 'flagbackup', 'clipzeros', 'quackinterval', 'quackmode', 'timecutoff', 'freqcutoff', 'timedev', 'freqdev', 'extendflags', 'extendpols'))
    return _run(
        "flagdata",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def flagmanager(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    mode: Literal['delete', 'list', 'rename', 'restore', 'save'] | object = _UNSET,
    versionname: str | object = _UNSET,
    oldname: str | object = _UNSET,
    comment: str | object = _UNSET,
    merge: Literal['and', 'or', 'replace'] | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Manage MeasurementSet flag-version snapshots."""
    overrides = _explicit(locals(), ('vis', 'mode', 'versionname', 'oldname', 'comment', 'merge'))
    return _run(
        "flagmanager",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def imcollapse(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    function: Literal['flux', 'max', 'mean', 'median', 'min', 'sqrtsum', 'stddev', 'sum'] | object = _UNSET,
    axes: int | object = _UNSET,
    outfile: StrPath | object = _UNSET,
    box: str | object = _UNSET,
    region: str | object = _UNSET,
    chans: str | object = _UNSET,
    stokes: str | object = _UNSET,
    mask: str | object = _UNSET,
    overwrite: bool | object = _UNSET,
    stretch: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Collapse image axes using CASA imcollapse."""
    overrides = _explicit(locals(), ('imagename', 'function', 'axes', 'outfile', 'box', 'region', 'chans', 'stokes', 'mask', 'overwrite', 'stretch'))
    return _run(
        "imcollapse",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def imfit(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    box: str | object = _UNSET,
    region: str | object = _UNSET,
    chans: str | object = _UNSET,
    stokes: str | object = _UNSET,
    mask: str | object = _UNSET,
    includepix: str | object = _UNSET,
    excludepix: str | object = _UNSET,
    residual: StrPath | object = _UNSET,
    model: StrPath | object = _UNSET,
    estimates: StrPath | object = _UNSET,
    logfile: StrPath | object = _UNSET,
    append: bool | object = _UNSET,
    newestimates: StrPath | object = _UNSET,
    complist: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    dooff: bool | object = _UNSET,
    offset: float | object = _UNSET,
    fixoffset: bool | object = _UNSET,
    stretch: str | object = _UNSET,
    rms: float | object = _UNSET,
    noisefwhm: str | object = _UNSET,
    summary: StrPath | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Fit Gaussian components using CASA imfit."""
    overrides = _explicit(locals(), ('imagename', 'box', 'region', 'chans', 'stokes', 'mask', 'includepix', 'excludepix', 'residual', 'model', 'estimates', 'logfile', 'append', 'newestimates', 'complist', 'overwrite', 'dooff', 'offset', 'fixoffset', 'stretch', 'rms', 'noisefwhm', 'summary'))
    return _run(
        "imfit",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def impbcor(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    pbimage: StrPath | object = _UNSET,
    outfile: StrPath | object = _UNSET,
    cutoff: float | object = _UNSET,
    box: str | object = _UNSET,
    region: str | object = _UNSET,
    chans: str | object = _UNSET,
    stokes: str | object = _UNSET,
    mask: str | object = _UNSET,
    mode: Literal['divide', 'multiply'] | object = _UNSET,
    overwrite: bool | object = _UNSET,
    stretch: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Apply primary-beam correction to a CASA image"""
    overrides = _explicit(locals(), ('imagename', 'pbimage', 'outfile', 'cutoff', 'box', 'region', 'chans', 'stokes', 'mask', 'mode', 'overwrite', 'stretch'))
    return _run(
        "impbcor",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def widebandpbcor(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    nterms: int | object = _UNSET,
    threshold: str | object = _UNSET,
    action: Literal['calcalpha', 'pbcor'] | object = _UNSET,
    reffreq: str | object = _UNSET,
    pbmin: float | object = _UNSET,
    field: str | object = _UNSET,
    spwlist: str | object = _UNSET,
    chanlist: str | object = _UNSET,
    weightlist: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Apply wideband primary-beam correction using CASA widebandpbcor."""
    overrides = _explicit(locals(), ('vis', 'imagename', 'nterms', 'threshold', 'action', 'reffreq', 'pbmin', 'field', 'spwlist', 'chanlist', 'weightlist'))
    return _run(
        "widebandpbcor",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def imcontsub(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    linefile: StrPath | object = _UNSET,
    contfile: StrPath | object = _UNSET,
    fitorder: int | object = _UNSET,
    region: str | object = _UNSET,
    box: str | object = _UNSET,
    chans: str | object = _UNSET,
    stokes: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Subtract image-cube continuum using CASA imcontsub."""
    overrides = _explicit(locals(), ('imagename', 'linefile', 'contfile', 'fitorder', 'region', 'box', 'chans', 'stokes'))
    return _run(
        "imcontsub",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def impv(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    outfile: StrPath | object = _UNSET,
    start: str | object = _UNSET,
    end: str | object = _UNSET,
    width: int | object = _UNSET,
    chans: str | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Extract a CASA-style position-velocity image"""
    overrides = _explicit(locals(), ('imagename', 'outfile', 'start', 'end', 'width', 'chans', 'overwrite'))
    return _run(
        "impv",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def imsubimage(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    outfile: StrPath | object = _UNSET,
    box: str | object = _UNSET,
    chans: str | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Extract a CASA-style image section"""
    overrides = _explicit(locals(), ('imagename', 'outfile', 'box', 'chans', 'overwrite'))
    return _run(
        "imsubimage",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def immath(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    expr: str | object = _UNSET,
    outfile: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Evaluate tutorial image arithmetic expressions"""
    overrides = _explicit(locals(), ('imagename', 'expr', 'outfile', 'overwrite'))
    return _run(
        "immath",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def imregrid(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    template: StrPath | object = _UNSET,
    output: StrPath | object = _UNSET,
    interpolation: Literal['linear', 'nearest'] | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Regrid a CASA image onto a template image"""
    overrides = _explicit(locals(), ('imagename', 'template', 'output', 'interpolation', 'overwrite'))
    return _run(
        "imregrid",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def feather(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    highres: StrPath | object = _UNSET,
    lowres: StrPath | object = _UNSET,
    sdfactor: float | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Combine high-resolution and low-resolution images in the Fourier domain"""
    overrides = _explicit(locals(), ('imagename', 'highres', 'lowres', 'sdfactor', 'overwrite'))
    return _run(
        "feather",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def importfits(
    *,
    fitsimage: StrPath | object = _UNSET,
    imagename: StrPath | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Import a FITS primary image into a CASA image"""
    overrides = _explicit(locals(), ('fitsimage', 'imagename', 'overwrite'))
    return _run(
        "importfits",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def concat(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    concatvis: StrPath | object = _UNSET,
    freqtol: str | object = _UNSET,
    dirtol: str | object = _UNSET,
    respectname: bool | object = _UNSET,
    timesort: bool | object = _UNSET,
    copypointing: bool | object = _UNSET,
    visweightscale: str | object = _UNSET,
    forcesingleephemfield: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Concatenate MeasurementSets using CASA concat."""
    overrides = _explicit(locals(), ('vis', 'concatvis', 'freqtol', 'dirtol', 'respectname', 'timesort', 'copypointing', 'visweightscale', 'forcesingleephemfield'))
    return _run(
        "concat",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def statwt(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    selectdata: bool | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    intent: str | object = _UNSET,
    array: str | object = _UNSET,
    observation: str | object = _UNSET,
    scan: str | object = _UNSET,
    combine: str | object = _UNSET,
    timebin: float | object = _UNSET,
    slidetimebin: bool | object = _UNSET,
    chanbin: int | object = _UNSET,
    minsamp: int | object = _UNSET,
    statalg: Literal['chauvenet', 'classic', 'fit-half', 'hinges-fences'] | object = _UNSET,
    fence: float | object = _UNSET,
    center: Literal['mean', 'median'] | object = _UNSET,
    lside: bool | object = _UNSET,
    zscore: float | object = _UNSET,
    maxiter: int | object = _UNSET,
    fitspw: str | object = _UNSET,
    excludechans: bool | object = _UNSET,
    wtrange: str | object = _UNSET,
    flagbackup: bool | object = _UNSET,
    preview: bool | object = _UNSET,
    datacolumn: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Compute and write visibility weights using CASA statwt."""
    overrides = _explicit(locals(), ('vis', 'selectdata', 'field', 'spw', 'intent', 'array', 'observation', 'scan', 'combine', 'timebin', 'slidetimebin', 'chanbin', 'minsamp', 'statalg', 'fence', 'center', 'lside', 'zscore', 'maxiter', 'fitspw', 'excludechans', 'wtrange', 'flagbackup', 'preview', 'datacolumn'))
    return _run(
        "statwt",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def hanningsmooth(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    outputvis: StrPath | object = _UNSET,
    keepmms: bool | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    scan: str | object = _UNSET,
    antenna: str | object = _UNSET,
    correlation: str | object = _UNSET,
    timerange: str | object = _UNSET,
    intent: str | object = _UNSET,
    array: str | object = _UNSET,
    uvrange: str | object = _UNSET,
    observation: str | object = _UNSET,
    feed: str | object = _UNSET,
    smooth_spw: str | object = _UNSET,
    datacolumn: str | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Hanning smooth channel data using CASA hanningsmooth."""
    overrides = _explicit(locals(), ('vis', 'outputvis', 'keepmms', 'field', 'spw', 'scan', 'antenna', 'correlation', 'timerange', 'intent', 'array', 'uvrange', 'observation', 'feed', 'smooth_spw', 'datacolumn'))
    return _run(
        "hanningsmooth",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def clearcal(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    intent: str | object = _UNSET,
    addmodel: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Reset calibration columns using CASA clearcal."""
    overrides = _explicit(locals(), ('vis', 'field', 'spw', 'intent', 'addmodel'))
    return _run(
        "clearcal",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def delmod(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    otf: bool | object = _UNSET,
    field: str | object = _UNSET,
    scr: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Delete MeasurementSet model data using CASA delmod."""
    overrides = _explicit(locals(), ('vis', 'otf', 'field', 'scr'))
    return _run(
        "delmod",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def ft(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    field: str | object = _UNSET,
    spw: str | object = _UNSET,
    model: str | object = _UNSET,
    nterms: int | object = _UNSET,
    reffreq: str | object = _UNSET,
    complist: StrPath | object = _UNSET,
    incremental: bool | object = _UNSET,
    usescratch: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Insert model visibilities using CASA ft."""
    overrides = _explicit(locals(), ('vis', 'field', 'spw', 'model', 'nterms', 'reffreq', 'complist', 'incremental', 'usescratch'))
    return _run(
        "ft",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def simanalyze(
    *,
    project: str | object = _UNSET,
    image: bool | object = _UNSET,
    imagename: StrPath | object = _UNSET,
    skymodel: StrPath | object = _UNSET,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] | object = _UNSET,
    modelimage: StrPath | object = _UNSET,
    imsize: int | list[int] | tuple[int, ...] | Literal['auto'] | object = _UNSET,
    imdirection: str | object = _UNSET,
    cell: str | list[str] | tuple[str, ...] | object = _UNSET,
    interactive: bool | object = _UNSET,
    niter: int | object = _UNSET,
    threshold: str | object = _UNSET,
    weighting: Literal['briggs', 'natural', 'uniform'] | object = _UNSET,
    mask: str | object = _UNSET,
    outertaper: str | object = _UNSET,
    pbcor: bool | object = _UNSET,
    stokes: str | object = _UNSET,
    featherimage: StrPath | object = _UNSET,
    analyze: bool | object = _UNSET,
    showuv: bool | object = _UNSET,
    showpsf: bool | object = _UNSET,
    showmodel: bool | object = _UNSET,
    showconvolved: bool | object = _UNSET,
    showclean: bool | object = _UNSET,
    showresidual: bool | object = _UNSET,
    showdifference: bool | object = _UNSET,
    showfidelity: bool | object = _UNSET,
    graphics: Literal['both', 'file', 'none', 'screen'] | object = _UNSET,
    verbose: bool | object = _UNSET,
    overwrite: bool | object = _UNSET,
    dryrun: bool | object = _UNSET,
    logfile: StrPath | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Image and analyze simulated observations using CASA simanalyze."""
    overrides = _explicit(locals(), ('project', 'image', 'imagename', 'skymodel', 'vis', 'modelimage', 'imsize', 'imdirection', 'cell', 'interactive', 'niter', 'threshold', 'weighting', 'mask', 'outertaper', 'pbcor', 'stokes', 'featherimage', 'analyze', 'showuv', 'showpsf', 'showmodel', 'showconvolved', 'showclean', 'showresidual', 'showdifference', 'showfidelity', 'graphics', 'verbose', 'overwrite', 'dryrun', 'logfile'))
    return _run(
        "simanalyze",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

def simalma(
    *,
    project: str | object = _UNSET,
    dryrun: bool | object = _UNSET,
    skymodel: StrPath | object = _UNSET,
    inbright: str | object = _UNSET,
    indirection: str | object = _UNSET,
    incell: str | object = _UNSET,
    incenter: str | object = _UNSET,
    inwidth: str | object = _UNSET,
    complist: StrPath | object = _UNSET,
    compwidth: str | object = _UNSET,
    setpointings: bool | object = _UNSET,
    ptgfile: StrPath | object = _UNSET,
    integration: str | object = _UNSET,
    direction: str | object = _UNSET,
    mapsize: str | object = _UNSET,
    antennalist: str | object = _UNSET,
    correlator: str | object = _UNSET,
    hourangle: str | object = _UNSET,
    totaltime: str | object = _UNSET,
    tpnant: int | object = _UNSET,
    tptime: str | object = _UNSET,
    pwv: float | object = _UNSET,
    image: bool | object = _UNSET,
    imsize: int | list[int] | tuple[int, ...] | Literal['auto'] | object = _UNSET,
    imdirection: str | object = _UNSET,
    cell: str | list[str] | tuple[str, ...] | object = _UNSET,
    niter: int | object = _UNSET,
    threshold: str | object = _UNSET,
    graphics: Literal['both', 'file', 'none', 'screen'] | object = _UNSET,
    verbose: bool | object = _UNSET,
    overwrite: bool | object = _UNSET,
    parameters: TaskParameters | None = None,
    profile: StrPath | None = None,
    base_source: Literal["defaults", "last", "last_successful"] = "defaults",
    workspace: StrPath | None = None,
    save_last: bool = True,
    binary: StrPath | None = None,
    check: bool = True,
    timeout: float | None = None,
    env: Mapping[str, str] | None = None,
    confirm_overwrite: bool = False,
    confirm_mutation: bool = False,
) -> TaskCompletion:
    """Run ALMA simulation workflows using CASA simalma."""
    overrides = _explicit(locals(), ('project', 'dryrun', 'skymodel', 'inbright', 'indirection', 'incell', 'incenter', 'inwidth', 'complist', 'compwidth', 'setpointings', 'ptgfile', 'integration', 'direction', 'mapsize', 'antennalist', 'correlator', 'hourangle', 'totaltime', 'tpnant', 'tptime', 'pwv', 'image', 'imsize', 'imdirection', 'cell', 'niter', 'threshold', 'graphics', 'verbose', 'overwrite'))
    return _run(
        "simalma",
        parameters=parameters,
        profile=profile,
        base_source=base_source,
        overrides=overrides,
        workspace=workspace,
        save_last=save_last,
        binary=binary,
        check=check,
        timeout=timeout,
        env=env,
        confirm_overwrite=confirm_overwrite,
        confirm_mutation=confirm_mutation,
    )

TASK_SURFACES = ('msexplore', 'calibrate', 'importvla', 'imager', 'simobserve', 'imhead', 'imstat', 'immoments', 'exportfits', 'mstransform', 'split', 'uvcontsub', 'applycal', 'gaincal', 'bandpass', 'fluxscale', 'gencal', 'plotms', 'plotcal', 'flagdata', 'flagmanager', 'imcollapse', 'imfit', 'impbcor', 'widebandpbcor', 'imcontsub', 'impv', 'imsubimage', 'immath', 'imregrid', 'feather', 'importfits', 'concat', 'statwt', 'hanningsmooth', 'clearcal', 'delmod', 'ft', 'simanalyze', 'simalma')

__all__ = ['TASK_SURFACES', 'msexplore', 'calibrate', 'importvla', 'imager', 'simobserve', 'imhead', 'imstat', 'immoments', 'exportfits', 'mstransform', 'split', 'uvcontsub', 'applycal', 'gaincal', 'bandpass', 'fluxscale', 'gencal', 'plotms', 'plotcal', 'flagdata', 'flagmanager', 'imcollapse', 'imfit', 'impbcor', 'widebandpbcor', 'imcontsub', 'impv', 'imsubimage', 'immath', 'imregrid', 'feather', 'importfits', 'concat', 'statwt', 'hanningsmooth', 'clearcal', 'delmod', 'ft', 'simanalyze', 'simalma']
