"""Generated CASA-named wrappers for every catalog task.

Do not edit by hand; run ``scripts/generate-python-parameter-wrappers.py``.
"""

from __future__ import annotations

from collections.abc import Mapping
from os import PathLike
from typing import Literal, TypeAlias

from ..parameters import ParameterData, TaskParameters
from ._runner import TaskCompletion, run as _run

StrPath: TypeAlias = str | PathLike[str]


def msexplore(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    format: Literal['json', 'text'] = ...,
    output: StrPath = ...,
    overwrite: bool = ...,
    selectdata: bool = ...,
    field: str = ...,
    spw: str = ...,
    timerange: str = ...,
    uvrange: str = ...,
    antenna: str = ...,
    scan: str = ...,
    correlation: str = ...,
    observation: str = ...,
    array: str = ...,
    intent: str = ...,
    feed: str = ...,
    msselect: str = ...,
    page_spec: StrPath = ...,
    preset: Literal['amplitude_phase_vs_time_stacked', 'amplitude_vs_channel', 'amplitude_vs_frequency', 'amplitude_vs_time', 'amplitude_vs_uv_distance', 'amplitude_vs_velocity', 'antenna_layout', 'azimuth_vs_elevation', 'azimuth_vs_time', 'elevation_vs_time', 'flag_vs_time', 'flagrow_vs_time', 'hour_angle_vs_time', 'none', 'parallactic_angle_vs_time', 'phase_vs_channel', 'phase_vs_frequency', 'phase_vs_time', 'phase_vs_velocity', 'real_vs_imaginary', 'scan_timeline', 'sigma_spectrum_vs_time', 'sigma_vs_time', 'spectral_window_coverage', 'uv_coverage', 'weight_spectrum_vs_time', 'weight_vs_time'] = ...,
    x_axis: str = ...,
    y_axis: str = ...,
    y_axis2: str = ...,
    datacolumn: str = ...,
    color_by: Literal['baseline', 'correlation', 'field', 'none', 'scan', 'spw'] = ...,
    avgchannel: int | Literal['none'] = ...,
    avgtime: float | Literal['none'] = ...,
    avgscan: bool = ...,
    avgfield: bool = ...,
    avgbaseline: bool = ...,
    avgantenna: bool = ...,
    avgspw: bool = ...,
    scalar: bool = ...,
    freqframe: Literal['BARY', 'CMB', 'GALACTO', 'GEO', 'LGROUP', 'LSRD', 'LSRK', 'TOPO', 'none'] = ...,
    restfreq: str = ...,
    veldef: Literal['OPTICAL', 'RADIO', 'TRUE'] = ...,
    iteraxis: Literal['correlation', 'field', 'none', 'scan', 'spw'] = ...,
    gridrows: int = ...,
    gridcols: int = ...,
    xselfscale: bool = ...,
    yselfscale: bool = ...,
    xsharedaxis: bool = ...,
    ysharedaxis: bool = ...,
    title: str = ...,
    xlabel: str = ...,
    ylabel: str = ...,
    symbol_size: float | Literal['none'] = ...,
    showlegend: bool = ...,
    legendposition: Literal['exteriorBottom', 'exteriorLeft', 'exteriorRight', 'exteriorTop', 'lowerLeft', 'lowerRight', 'upperLeft', 'upperRight'] = ...,
    showmajorgrid: bool = ...,
    showminorgrid: bool = ...,
    headeritems: str = ...,
    max_points: int = ...,
    plot_output: StrPath = ...,
    plot_format: Literal['pdf', 'png', 'txt'] = ...,
    plot_width: int = ...,
    plot_height: int = ...,
    flag_action: Literal['flag', 'none', 'unflag'] = ...,
    flag_xmin: float | Literal['none'] = ...,
    flag_xmax: float | Literal['none'] = ...,
    flag_ymin: float | Literal['none'] = ...,
    flag_ymax: float | Literal['none'] = ...,
    flag_plotindex: int | Literal['none'] = ...,
    flag_panel: str = ...,
    flag_extcorr: bool = ...,
    flag_extchannel: bool = ...,
    flag_selected: bool = ...,
    flag_apply: bool = ...,
    flag_output: StrPath = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def calibrate(
    *,
    mode: Literal['apply', 'continuum_subtract', 'export_corrected_data', 'fluxscale', 'gencal', 'solve_bandpass', 'solve_gain', 'stats', 'summary'] = ...,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    outputvis: StrPath = ...,
    summary_paths: str = ...,
    gaintables: str = ...,
    table_path: StrPath = ...,
    callib: StrPath = ...,
    gainfield: str = ...,
    interp: str = ...,
    spwmap: str = ...,
    apply_mode: Literal['calflag', 'calonly', 'trial'] = ...,
    calwt: str = ...,
    output: StrPath = ...,
    overwrite: bool = ...,
    parang: bool = ...,
    format: Literal['json', 'text'] = ...,
    stats_axis: Literal['amp', 'imag', 'phase', 'real'] = ...,
    stats_datacolumn: str = ...,
    fit_spw: str = ...,
    use_flags: bool = ...,
    fit_order: int = ...,
    out_table: StrPath = ...,
    refant: str = ...,
    gain_type: Literal['g', 't'] = ...,
    solve_mode: Literal['ap', 'p'] = ...,
    solint: str = ...,
    gain_combine: str = ...,
    gain_model_source: Literal['model-column', 'point'] = ...,
    smodel: str = ...,
    min_snr: float = ...,
    bandpass_combine: Literal['field', 'none', 'scan', 'scan,field'] = ...,
    bandtype: Literal['b', 'bpoly'] = ...,
    solnorm: bool = ...,
    fluxscale_input: StrPath = ...,
    reference_fields: str = ...,
    transfer_fields: str = ...,
    refspwmap: str = ...,
    gainthreshold: float | Literal['none'] = ...,
    incremental: bool = ...,
    selectdata: bool = ...,
    field: str = ...,
    spw: str = ...,
    antenna: str = ...,
    scan: str = ...,
    observation: str = ...,
    array: str = ...,
    timerange: str = ...,
    msselect: str = ...,
    caltype: Literal['antpos', 'gceff', 'opac'] | Literal['none'] = ...,
    parameter: str = ...,
    gaincurve_table: StrPath = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def importvla(
    *,
    archivefiles: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    bandname: Literal['4', 'C', 'K', 'Ka', 'L', 'P', 'Q', 'S', 'U', 'X', 'none'] = ...,
    frequencytol: str = ...,
    project: str = ...,
    starttime: str = ...,
    stoptime: str = ...,
    applytsys: bool = ...,
    autocorr: bool = ...,
    antnamescheme: Literal['new', 'old'] = ...,
    keepblanks: bool = ...,
    evlabands: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def imager(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    imagename: StrPath = ...,
    imsize: int | list[int] | tuple[int, ...] | Literal['auto'] = ...,
    cell: str | list[str] | tuple[str, ...] = ...,
    datacolumn: str = ...,
    savemodel: Literal['modelcolumn', 'none'] = ...,
    startmodel: StrPath = ...,
    outlierfile: StrPath = ...,
    field: str = ...,
    phasecenter_field: str = ...,
    ddid: str = ...,
    phasecenter: str = ...,
    spw: str = ...,
    channel_start: int | Literal['none'] = ...,
    channel_count: int | Literal['none'] = ...,
    polarization: Literal['I', 'LL', 'Q', 'RR', 'U', 'V', 'XX', 'YY'] = ...,
    specmode: Literal['cube', 'cubedata', 'mfs'] = ...,
    start: str = ...,
    width: int | Literal['none'] = ...,
    outframe: Literal['BARY', 'CMB', 'GALACTO', 'GEO', 'LGROUP', 'LSRD', 'LSRK', 'REST', 'TOPO', 'none'] = ...,
    veltype: Literal['BETA', 'GAMMA', 'OPTICAL', 'RADIO', 'TRUE', 'none'] = ...,
    interpolation: Literal['cubic', 'linear', 'nearest', 'none'] = ...,
    restfreq: str = ...,
    restoringbeam: Literal['common', 'none'] = ...,
    perchanweightdensity: bool = ...,
    dirty_only: bool = ...,
    niter: int = ...,
    threshold: str = ...,
    nmajor: int = ...,
    fullsummary: bool = ...,
    gain: float = ...,
    nsigma: float = ...,
    psfcutoff: float = ...,
    minor_cycle_length: int = ...,
    cyclefactor: float = ...,
    deconvolver: Literal['clark', 'hogbom', 'mtmfs', 'multiscale'] = ...,
    minpsffraction: float = ...,
    maxpsffraction: float = ...,
    nterms: int = ...,
    hogbom_iteration_mode: str = ...,
    scales: str = ...,
    smallscalebias: float = ...,
    usemask: Literal['auto-multithresh', 'user'] = ...,
    sidelobethreshold: float = ...,
    noisethreshold: float = ...,
    lownoisethreshold: float = ...,
    negativethreshold: float = ...,
    minbeamfrac: float = ...,
    growiterations: int = ...,
    mask_box: str = ...,
    weighting: Literal['briggs', 'briggsbwtaper', 'natural', 'uniform'] = ...,
    mask_image: StrPath = ...,
    robust: float = ...,
    wprojplanes: int | Literal['none'] = ...,
    usepointing: bool = ...,
    uvtaper: str = ...,
    write_preview_pngs: bool = ...,
    write_pb: bool = ...,
    pbcor: bool = ...,
    pblimit: float = ...,
    wterm: Literal['direct', 'none', 'wproject'] = ...,
    gridder: Literal['awp2', 'awphpg', 'awproject', 'mosaic', 'standard', 'widefield', 'wproject'] = ...,
    standard_mfs_acceleration: Literal['auto', 'cpu', 'metal', 'multi-cpu'] = ...,
    parallel: bool | Literal['none'] = ...,
    imaging_read_ahead_blocks: int | Literal['none'] = ...,
    imaging_fft_backend: Literal['accelerate', 'auto', 'metal-mpsgraph', 'rustfft'] = ...,
    chanchunks: int | Literal['none'] = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def simobserve(
    *,
    request_kind: Literal['family', 'run'] = ...,
    model: StrPath = ...,
    out: StrPath = ...,
    inbright: str = ...,
    duration: float = ...,
    integration: str = ...,
    start_frequency_hz: float = ...,
    channel_width_hz: float = ...,
    channel_count: int | Literal['none'] = ...,
    overwrite: bool = ...,
    predict_model: bool = ...,
    polarizations: str = ...,
    polarization_basis: str = ...,
    worker_policy: Literal['auto', 'fixed'] = ...,
    row_workers: int | Literal['none'] = ...,
    channel_workers: int | Literal['none'] = ...,
    corruption_seed: str = ...,
    noise_simplenoise_jy: float | Literal['none'] = ...,
    gain_mode: str = ...,
    gain_interval_seconds: float = ...,
    gain_amplitude: str = ...,
    bandpass_mode: str = ...,
    bandpass_interval_seconds: float = ...,
    bandpass_amplitude: str = ...,
    leakage_amplitude: str = ...,
    leakage_offset: str = ...,
    pointing_offset_ra_arcsec: float | Literal['none'] = ...,
    pointing_offset_dec_arcsec: float | Literal['none'] = ...,
    source_model: str = ...,
    telescope: Literal['ACA', 'ALMA', 'VLA'] = ...,
    array_config: Literal['A', 'aca.cycle10.cfg', 'alma.cycle10.5.cfg', 'synthetic-aca', 'synthetic-alma-compact', 'synthetic-simalma', 'synthetic-vla-d', 'vla.b.cfg', 'vla.c.cfg', 'vla.d.cfg'] = ...,
    band: Literal['Band 3', 'Band 6', 'Band 7', 'Band 9', 'C', 'K', 'Ka', 'Ku', 'L', 'Q', 'S', 'X'] = ...,
    target_ms_size_gib: float = ...,
    output_ms: StrPath = ...,
    ms_channels: int = ...,
    image_channels: int = ...,
    pointing_count: int = ...,
    time_sample_count: int | Literal['none'] = ...,
    integration_seconds: float | Literal['none'] = ...,
    start_time_mjd_seconds: float | Literal['none'] = ...,
    imaging_mode: Literal['aca', 'continuum', 'continuum_mfs', 'cube', 'cubedata', 'mfs', 'mosaic', 'mosaic_mfs', 'mt_mfs', 'simalma', 'single_field', 'spectral_cube'] = ...,
    observation_mode: Literal['interferometric', 'total_power'] = ...,
    measure_actual_size: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def imhead(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    mode: Literal['list', 'put', 'summary'] = ...,
    hdkey: str = ...,
    hdvalue: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def imstat(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    box: str = ...,
    region: str = ...,
    chans: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def immoments(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    outfile: StrPath = ...,
    moments: Literal['-1', '0', '1', '2', '3'] = ...,
    chans: str = ...,
    includepix: str = ...,
    mask: str = ...,
    overwrite: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def exportfits(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    fitsimage: StrPath = ...,
    velocity: bool = ...,
    overwrite: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def mstransform(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    outputvis: StrPath = ...,
    spw: str = ...,
    width: int = ...,
    field: str = ...,
    scan: str = ...,
    antenna: str = ...,
    timerange: str = ...,
    msselect: str = ...,
    datacolumn: str = ...,
    keepflags: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def split(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    outputvis: StrPath = ...,
    spw: str = ...,
    width: int = ...,
    field: str = ...,
    scan: str = ...,
    antenna: str = ...,
    timerange: str = ...,
    msselect: str = ...,
    datacolumn: str = ...,
    keepflags: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def uvcontsub(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    outputvis: StrPath = ...,
    output: StrPath = ...,
    overwrite: bool = ...,
    format: Literal['json', 'text'] = ...,
    stats_datacolumn: str = ...,
    fit_spw: str = ...,
    fit_order: int = ...,
    selectdata: bool = ...,
    field: str = ...,
    spw: str = ...,
    antenna: str = ...,
    scan: str = ...,
    observation: str = ...,
    array: str = ...,
    timerange: str = ...,
    msselect: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def applycal(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    gaintables: str = ...,
    callib: StrPath = ...,
    gainfield: str = ...,
    interp: str = ...,
    spwmap: str = ...,
    apply_mode: Literal['calflag', 'calonly', 'trial'] = ...,
    calwt: str = ...,
    output: StrPath = ...,
    overwrite: bool = ...,
    parang: bool = ...,
    format: Literal['json', 'text'] = ...,
    selectdata: bool = ...,
    field: str = ...,
    spw: str = ...,
    antenna: str = ...,
    scan: str = ...,
    observation: str = ...,
    array: str = ...,
    timerange: str = ...,
    msselect: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def gaincal(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    gaintables: str = ...,
    callib: StrPath = ...,
    gainfield: str = ...,
    interp: str = ...,
    spwmap: str = ...,
    output: StrPath = ...,
    overwrite: bool = ...,
    format: Literal['json', 'text'] = ...,
    out_table: StrPath = ...,
    refant: str = ...,
    gain_type: Literal['g', 't'] = ...,
    solve_mode: Literal['ap', 'p'] = ...,
    solint: str = ...,
    gain_combine: str = ...,
    gain_model_source: Literal['model-column', 'point'] = ...,
    smodel: str = ...,
    min_snr: float = ...,
    solnorm: bool = ...,
    selectdata: bool = ...,
    field: str = ...,
    spw: str = ...,
    antenna: str = ...,
    scan: str = ...,
    observation: str = ...,
    array: str = ...,
    timerange: str = ...,
    msselect: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def bandpass(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    gaintables: str = ...,
    callib: StrPath = ...,
    gainfield: str = ...,
    interp: str = ...,
    spwmap: str = ...,
    output: StrPath = ...,
    overwrite: bool = ...,
    format: Literal['json', 'text'] = ...,
    out_table: StrPath = ...,
    refant: str = ...,
    smodel: str = ...,
    min_snr: float = ...,
    bandpass_combine: Literal['field', 'none', 'scan', 'scan,field'] = ...,
    bandtype: Literal['b', 'bpoly'] = ...,
    solnorm: bool = ...,
    selectdata: bool = ...,
    field: str = ...,
    spw: str = ...,
    antenna: str = ...,
    scan: str = ...,
    observation: str = ...,
    array: str = ...,
    timerange: str = ...,
    msselect: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def fluxscale(
    *,
    output: StrPath = ...,
    overwrite: bool = ...,
    format: Literal['json', 'text'] = ...,
    out_table: StrPath = ...,
    fluxscale_input: StrPath = ...,
    reference_fields: str = ...,
    transfer_fields: str = ...,
    refspwmap: str = ...,
    gainthreshold: float | Literal['none'] = ...,
    incremental: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def gencal(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    output: StrPath = ...,
    overwrite: bool = ...,
    format: Literal['json', 'text'] = ...,
    out_table: StrPath = ...,
    caltype: Literal['antpos', 'gceff', 'opac'] | Literal['none'] = ...,
    parameter: str = ...,
    gaincurve_table: StrPath = ...,
    spw: str = ...,
    antenna: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def plotms(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    format: Literal['json', 'text'] = ...,
    output: StrPath = ...,
    overwrite: bool = ...,
    selectdata: bool = ...,
    field: str = ...,
    spw: str = ...,
    timerange: str = ...,
    uvrange: str = ...,
    antenna: str = ...,
    scan: str = ...,
    correlation: str = ...,
    observation: str = ...,
    array: str = ...,
    intent: str = ...,
    feed: str = ...,
    msselect: str = ...,
    page_spec: StrPath = ...,
    preset: Literal['amplitude_phase_vs_time_stacked', 'amplitude_vs_channel', 'amplitude_vs_frequency', 'amplitude_vs_time', 'amplitude_vs_uv_distance', 'amplitude_vs_velocity', 'antenna_layout', 'azimuth_vs_elevation', 'azimuth_vs_time', 'elevation_vs_time', 'flag_vs_time', 'flagrow_vs_time', 'hour_angle_vs_time', 'none', 'parallactic_angle_vs_time', 'phase_vs_channel', 'phase_vs_frequency', 'phase_vs_time', 'phase_vs_velocity', 'real_vs_imaginary', 'scan_timeline', 'sigma_spectrum_vs_time', 'sigma_vs_time', 'spectral_window_coverage', 'uv_coverage', 'weight_spectrum_vs_time', 'weight_vs_time'] = ...,
    x_axis: str = ...,
    y_axis: str = ...,
    y_axis2: str = ...,
    datacolumn: str = ...,
    color_by: Literal['baseline', 'correlation', 'field', 'none', 'scan', 'spw'] = ...,
    avgchannel: int | Literal['none'] = ...,
    avgtime: float | Literal['none'] = ...,
    avgscan: bool = ...,
    avgfield: bool = ...,
    avgbaseline: bool = ...,
    avgantenna: bool = ...,
    avgspw: bool = ...,
    scalar: bool = ...,
    freqframe: Literal['BARY', 'CMB', 'GALACTO', 'GEO', 'LGROUP', 'LSRD', 'LSRK', 'TOPO', 'none'] = ...,
    restfreq: str = ...,
    veldef: Literal['OPTICAL', 'RADIO', 'TRUE'] = ...,
    iteraxis: Literal['correlation', 'field', 'none', 'scan', 'spw'] = ...,
    gridrows: int = ...,
    gridcols: int = ...,
    xselfscale: bool = ...,
    yselfscale: bool = ...,
    xsharedaxis: bool = ...,
    ysharedaxis: bool = ...,
    title: str = ...,
    xlabel: str = ...,
    ylabel: str = ...,
    symbol_size: float | Literal['none'] = ...,
    showlegend: bool = ...,
    legendposition: Literal['exteriorBottom', 'exteriorLeft', 'exteriorRight', 'exteriorTop', 'lowerLeft', 'lowerRight', 'upperLeft', 'upperRight'] = ...,
    showmajorgrid: bool = ...,
    showminorgrid: bool = ...,
    headeritems: str = ...,
    max_points: int = ...,
    plot_output: StrPath = ...,
    plot_format: Literal['pdf', 'png', 'txt'] = ...,
    plot_width: int = ...,
    plot_height: int = ...,
    flag_action: Literal['flag', 'none', 'unflag'] = ...,
    flag_xmin: float | Literal['none'] = ...,
    flag_xmax: float | Literal['none'] = ...,
    flag_ymin: float | Literal['none'] = ...,
    flag_ymax: float | Literal['none'] = ...,
    flag_plotindex: int | Literal['none'] = ...,
    flag_panel: str = ...,
    flag_extcorr: bool = ...,
    flag_extchannel: bool = ...,
    flag_selected: bool = ...,
    flag_apply: bool = ...,
    flag_output: StrPath = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def plotcal(
    *,
    caltable: StrPath = ...,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    preset: Literal['bandpass_amplitude_vs_frequency', 'bandpass_phase_vs_frequency', 'corrected_amplitude_vs_frequency', 'corrected_amplitude_vs_time', 'corrected_phase_vs_frequency', 'corrected_phase_vs_time', 'gain_amplitude_vs_time', 'gain_phase_vs_time'] = ...,
    field: str = ...,
    spw: str = ...,
    timerange: str = ...,
    uvrange: str = ...,
    antenna: str = ...,
    scan: str = ...,
    correlation: str = ...,
    observation: str = ...,
    array: str = ...,
    intent: str = ...,
    feed: str = ...,
    msselect: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def flagdata(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    mode: Literal['clip', 'extend', 'manual', 'quack', 'rflag', 'summary', 'tfcrop'] = ...,
    spw: str = ...,
    field: str = ...,
    scan: str = ...,
    antenna: str = ...,
    datacolumn: str = ...,
    action: Literal['flag', 'unflag'] = ...,
    flagbackup: bool = ...,
    clipzeros: bool = ...,
    quackinterval: float = ...,
    quackmode: Literal['beg', 'end'] = ...,
    timecutoff: float = ...,
    freqcutoff: float = ...,
    timedev: float | Literal['none'] = ...,
    freqdev: float | Literal['none'] = ...,
    extendflags: bool = ...,
    extendpols: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def flagmanager(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    mode: Literal['delete', 'list', 'rename', 'restore', 'save'] = ...,
    versionname: str = ...,
    oldname: str = ...,
    comment: str = ...,
    merge: Literal['and', 'or', 'replace'] = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def imcollapse(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    function: Literal['flux', 'max', 'mean', 'median', 'min', 'sqrtsum', 'stddev', 'sum'] = ...,
    axes: int = ...,
    outfile: StrPath = ...,
    box: str = ...,
    region: str = ...,
    chans: str = ...,
    stokes: str = ...,
    mask: str = ...,
    overwrite: bool = ...,
    stretch: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def imfit(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    box: str = ...,
    region: str = ...,
    chans: str = ...,
    stokes: str = ...,
    mask: str = ...,
    includepix: str = ...,
    excludepix: str = ...,
    residual: StrPath = ...,
    model: StrPath = ...,
    estimates: StrPath = ...,
    logfile: StrPath = ...,
    append: bool = ...,
    newestimates: StrPath = ...,
    complist: StrPath = ...,
    overwrite: bool = ...,
    dooff: bool = ...,
    offset: float = ...,
    fixoffset: bool = ...,
    stretch: str = ...,
    rms: float = ...,
    noisefwhm: str = ...,
    summary: StrPath = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def impbcor(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    pbimage: StrPath = ...,
    outfile: StrPath = ...,
    cutoff: float = ...,
    box: str = ...,
    region: str = ...,
    chans: str = ...,
    stokes: str = ...,
    mask: str = ...,
    mode: Literal['divide', 'multiply'] = ...,
    overwrite: bool = ...,
    stretch: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def widebandpbcor(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    nterms: int = ...,
    threshold: str = ...,
    action: Literal['calcalpha', 'pbcor'] = ...,
    reffreq: str = ...,
    pbmin: float = ...,
    field: str = ...,
    spwlist: str = ...,
    chanlist: str = ...,
    weightlist: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def imcontsub(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    linefile: StrPath = ...,
    contfile: StrPath = ...,
    fitorder: int = ...,
    region: str = ...,
    box: str = ...,
    chans: str = ...,
    stokes: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def impv(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    outfile: StrPath = ...,
    start: str = ...,
    end: str = ...,
    width: int = ...,
    chans: str = ...,
    overwrite: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def imsubimage(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    outfile: StrPath = ...,
    box: str = ...,
    chans: str = ...,
    overwrite: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def immath(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    expr: str = ...,
    outfile: StrPath = ...,
    overwrite: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def imregrid(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    template: StrPath = ...,
    output: StrPath = ...,
    interpolation: Literal['linear', 'nearest'] = ...,
    overwrite: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def feather(
    *,
    imagename: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    highres: StrPath = ...,
    lowres: StrPath = ...,
    sdfactor: float = ...,
    overwrite: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def importfits(
    *,
    fitsimage: StrPath = ...,
    imagename: StrPath = ...,
    overwrite: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def concat(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    concatvis: StrPath = ...,
    freqtol: str = ...,
    dirtol: str = ...,
    respectname: bool = ...,
    timesort: bool = ...,
    copypointing: bool = ...,
    visweightscale: str = ...,
    forcesingleephemfield: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def statwt(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    selectdata: bool = ...,
    field: str = ...,
    spw: str = ...,
    intent: str = ...,
    array: str = ...,
    observation: str = ...,
    scan: str = ...,
    combine: str = ...,
    timebin: float = ...,
    slidetimebin: bool = ...,
    chanbin: int = ...,
    minsamp: int = ...,
    statalg: Literal['chauvenet', 'classic', 'fit-half', 'hinges-fences'] = ...,
    fence: float = ...,
    center: Literal['mean', 'median'] = ...,
    lside: bool = ...,
    zscore: float = ...,
    maxiter: int = ...,
    fitspw: str = ...,
    excludechans: bool = ...,
    wtrange: str = ...,
    flagbackup: bool = ...,
    preview: bool = ...,
    datacolumn: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def hanningsmooth(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    outputvis: StrPath = ...,
    keepmms: bool = ...,
    field: str = ...,
    spw: str = ...,
    scan: str = ...,
    antenna: str = ...,
    correlation: str = ...,
    timerange: str = ...,
    intent: str = ...,
    array: str = ...,
    uvrange: str = ...,
    observation: str = ...,
    feed: str = ...,
    smooth_spw: str = ...,
    datacolumn: str = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def clearcal(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    field: str = ...,
    spw: str = ...,
    intent: str = ...,
    addmodel: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def delmod(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    otf: bool = ...,
    field: str = ...,
    scr: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def ft(
    *,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    field: str = ...,
    spw: str = ...,
    model: str = ...,
    nterms: int = ...,
    reffreq: str = ...,
    complist: StrPath = ...,
    incremental: bool = ...,
    usescratch: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def simanalyze(
    *,
    project: str = ...,
    image: bool = ...,
    imagename: StrPath = ...,
    skymodel: StrPath = ...,
    vis: StrPath | list[StrPath] | tuple[StrPath, ...] = ...,
    modelimage: StrPath = ...,
    imsize: int | list[int] | tuple[int, ...] | Literal['auto'] = ...,
    imdirection: str = ...,
    cell: str | list[str] | tuple[str, ...] = ...,
    interactive: bool = ...,
    niter: int = ...,
    threshold: str = ...,
    weighting: Literal['briggs', 'natural', 'uniform'] = ...,
    mask: str = ...,
    outertaper: str = ...,
    pbcor: bool = ...,
    stokes: str = ...,
    featherimage: StrPath = ...,
    analyze: bool = ...,
    showuv: bool = ...,
    showpsf: bool = ...,
    showmodel: bool = ...,
    showconvolved: bool = ...,
    showclean: bool = ...,
    showresidual: bool = ...,
    showdifference: bool = ...,
    showfidelity: bool = ...,
    graphics: Literal['both', 'file', 'none', 'screen'] = ...,
    verbose: bool = ...,
    overwrite: bool = ...,
    dryrun: bool = ...,
    logfile: StrPath = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

def simalma(
    *,
    project: str = ...,
    dryrun: bool = ...,
    skymodel: StrPath = ...,
    inbright: str = ...,
    indirection: str = ...,
    incell: str = ...,
    incenter: str = ...,
    inwidth: str = ...,
    complist: StrPath = ...,
    compwidth: str = ...,
    setpointings: bool = ...,
    ptgfile: StrPath = ...,
    integration: str = ...,
    direction: str = ...,
    mapsize: str = ...,
    antennalist: str = ...,
    correlator: str = ...,
    hourangle: str = ...,
    totaltime: str = ...,
    tpnant: int = ...,
    tptime: str = ...,
    pwv: float = ...,
    image: bool = ...,
    imsize: int | list[int] | tuple[int, ...] | Literal['auto'] = ...,
    imdirection: str = ...,
    cell: str | list[str] | tuple[str, ...] = ...,
    niter: int = ...,
    threshold: str = ...,
    graphics: Literal['both', 'file', 'none', 'screen'] = ...,
    verbose: bool = ...,
    overwrite: bool = ...,
    parameters: TaskParameters | None = ...,
    profile: StrPath | None = ... ,
    base_source: Literal["defaults", "last", "last_successful"] = ... ,
    workspace: StrPath | None = ... ,
    save_last: bool = ... ,
    binary: StrPath | None = ... ,
    check: bool = ... ,
    timeout: float | None = ... ,
    env: Mapping[str, str] | None = ... ,
    confirm_overwrite: bool = ... ,
    confirm_mutation: bool = ... ,
) -> TaskCompletion:
    ...

TASK_SURFACES = ('msexplore', 'calibrate', 'importvla', 'imager', 'simobserve', 'imhead', 'imstat', 'immoments', 'exportfits', 'mstransform', 'split', 'uvcontsub', 'applycal', 'gaincal', 'bandpass', 'fluxscale', 'gencal', 'plotms', 'plotcal', 'flagdata', 'flagmanager', 'imcollapse', 'imfit', 'impbcor', 'widebandpbcor', 'imcontsub', 'impv', 'imsubimage', 'immath', 'imregrid', 'feather', 'importfits', 'concat', 'statwt', 'hanningsmooth', 'clearcal', 'delmod', 'ft', 'simanalyze', 'simalma')

__all__ = ['TASK_SURFACES', 'msexplore', 'calibrate', 'importvla', 'imager', 'simobserve', 'imhead', 'imstat', 'immoments', 'exportfits', 'mstransform', 'split', 'uvcontsub', 'applycal', 'gaincal', 'bandpass', 'fluxscale', 'gencal', 'plotms', 'plotcal', 'flagdata', 'flagmanager', 'imcollapse', 'imfit', 'impbcor', 'widebandpbcor', 'imcontsub', 'impv', 'imsubimage', 'immath', 'imregrid', 'feather', 'importfits', 'concat', 'statwt', 'hanningsmooth', 'clearcal', 'delmod', 'ft', 'simanalyze', 'simalma']
